### ISSUE TITLE
Submenus

### ISSUE THREAD

**Issue by gaztelugatxe** [lxndrblz/anatole#101]
I cannot get the submenus to work as I think they should in Hugo, so I am thinking they are not supported in Anatole. Is it so?
Thanks in advance!

**Comment by lxndrblz** [comment]
Regrettably that is currently not possible.On Dec 24, 2020 6:43 PM, gaztelugatxe <notifications@github.com> wrote:
I cannot get the submenus to work as I think they should in Hugo, so I am thinking they are not supported in Anatole. Is it so?
Thanks in advance!
