### ISSUE TITLE
Theme colors customization

### ISSUE THREAD

**Issue by sschizas** [lxndrblz/anatole#106]
Hello and HNY!!

how I can customize the colors of the theme? I checked the read me file and I haven't seen any relevant information.

Kind regards,
Stavros

**Comment by lxndrblz** [comment]
@sschizas  You can set the preferred theme mode through the `config.toml`. If you want to tweak a certain colour, you would have to overwrite them with a custom css file.

Hope that helps.

**Comment by sschizas** [comment]
@lxndrblz so if I got right, I have to make a copy of https://github.com/lxndrblz/anatole/blob/master/assets/css/style.css and change the colors and set the path of the custom CSS file at the config file, right?

**Comment by lxndrblz** [comment]
@sschizas no need to copy the whole file for minor tweaks. You Only need to add the things you want changed. Simply use the inspector in the Browser to find out the relevant css classes and overwrite the matching css variables.

If you have any technical issues, let me know.
