### ISSUE TITLE
How can I remove the profile_picture?

### ISSUE THREAD

**Issue by belxc** [lxndrblz/anatole#115]
- I know this is a noob question, but how can I remove the `profile_picture` on the left page, :) , while I did not wrote the `profile picture`'s URL .the webpage will show  `profile picture` top the name .
> I mean `profile_picture` this word show on my page  , I dont want image
- can I have a menu named `tags` , to show all of the tags that I have 
sorry , I just a novice  . thanks

**Comment by lxndrblz** [comment]
@belxc  There is no effortless way to remove the profile picture as it's a central part of the theme. If you would want to remove it, then I'd recommend cloning the theme and removing it in the html of the sidebar.

Yes you can. Simply add another menu entry that points to `/tags/` like this:
```
[menu]

  [[menu.main]]
  name = "Tags"
  identifier = "tags"
  weight = 100
  url = "/tags/"
```
If you want to edit the presentation of the tags listing and the individual tags then, please see this issue #99.

**Comment by belxc** [comment]
@lxndrblz  Thanks . I have to say , it is a great theme.

**Comment by lxndrblz** [comment]
@belxc Great to hear that. I will close the issue. Feel free to open a new one, if more questions arise.

**Comment by shariq1989** [comment]
@lxndrblz, great work on the theme. I'd like to override and make some changes particular to my usecase. Is the process for cloning and pointing to that theme outlined anywhere?

**Comment by lxndrblz** [comment]
@shariq1989 simply run a `git clone https://github.com/lxndrblz/anatole.git anatole` and make the necessary changes locally. Alternatively you can also fork it.

**Comment by shariq1989** [comment]
Makes sense, I'll fork it. 

For anyone needing some documentation on this:
https://www.andrewhoog.com/post/git-submodule-for-hugo-themes/

**Comment by lxndrblz** [comment]
@shariq1989 That article is very helpful for understanding the different concepts of how themes can be added. We generally encourage submodules as they allow for a n easy update. Patching certain components is a bit more difficult. Other themes recommend cloning which makes it easy to adjust things but difficult to update. Obviously both approaches have there ups and downs. By forking and adding the fork as a submodule you should be able to get the best of both worlds.

Let me know there is a certain command you would have like to seen in the Readme which helped you getting started.
