### ISSUE TITLE
New Feature Query: Netlify form integration

### ISSUE THREAD

**Issue by cdichiara** [lxndrblz/anatole#117]
My feeling is ... yes, people are probably using Netlify a lot to host, having an integrated form might be useful.

As compared to Formspree, there's no separate URL to send the form in - but we need a unique name for each contact form. So we'd need to figure out a way to indicate the unique name in the frontmatter of the page, or use the name of the page to generate the singular contact form allowed on each page. I vote for using the page name or the relative path somehow.

Otherwise we're pretty much already set up to support Netlify forms, so just let me know about whether you want the feature.

Carmine

**Comment by lxndrblz** [comment]
@cdichiara  Yes, that sounds like a good idea. I think we could use a parameter in the frontmatter to specify a certain contact form. Would you mind submitting a sperate PR for this feature once it is ready?

**Comment by cdichiara** [comment]
Yes that's fine, it'll be subsequent to the other pull request. We can discuss whether we need to make the default backwards-compatible, it makes the logic much harder.

**Comment by lxndrblz** [comment]
Further discussions will be carried out in PR #121 .
