### ISSUE TITLE
Exporting Jupyter Notebooks to be used with Anatole in Hugo

### ISSUE THREAD

**Issue by Liam427** [lxndrblz/anatole#127]
![jupyter](https://user-images.githubusercontent.com/75194319/105632839-a6b74280-5e98-11eb-81d5-73b7115f8be0.PNG)
Please read it considering that I am not good at English.
Ah! And I'm not good at computers.
I just started studying data science.
I'm sorry. :sob:
I want to post by converting to markdown using jupyter notebook.
So, the method I found is nb2hugo, which is a little inconvenient, but I am using it.
The inconvenient point is that you have to enter the address on the graph image.
But it seems to be okay when I try it for practice.
However, one problem is that the dataframe is output like a capture.
So I tried to modify the css, but couldn't get any information about it.
Please help me.
Once again, the theme is so pretty and I use it well. 👍

**Comment by lxndrblz** [comment]
Hi @Liam427, I'm glad you like the theme!

Indeed, I had a little bit of trouble understanding what you meant. To me the marked area just looks like a code block of *CSS*. By default, this does not get interpreted by the theme. I imagine the data frame should be output as a table. Would you mind sharing what your *Jupyter* notebook looks like and what is in your generated *Markdown* file?

**Comment by Liam427** [comment]
![1](https://user-images.githubusercontent.com/75194319/105649523-f0814680-5ef3-11eb-9a8a-f6e68c43539b.PNG)
![2](https://user-images.githubusercontent.com/75194319/105649527-f37c3700-5ef3-11eb-9a38-107d26aeaf5f.PNG)
![3](https://user-images.githubusercontent.com/75194319/105649529-f545fa80-5ef3-11eb-9936-f428e790d23e.PNG)
![4](https://user-images.githubusercontent.com/75194319/105649535-f70fbe00-5ef3-11eb-929d-de065674edaf.PNG)
Then can you help me to decorate the css file?
As shown, the dataframe output of markdown is shown on the blog as it is.
Before posting the question, I thought that the solution was to decorate the css file rather than the theme problem.
However, I was afraid that the internal codes would crash.
I ask for your high insight. :pray:

**Comment by Liam427** [comment]
I asked around and resolved it.
Thank you for caring me. 💯
