### ISSUE TITLE
Misaligned post dates with long title

### ISSUE THREAD

**Issue by cwpearson** [lxndrblz/anatole#129]
Hi, I'm experimenting with using this theme for a resume-style personal site. I have several published papers I'm modeling as posts, but some have quite long titles and it seems to cause the dates in the list to be misaligned at certain window widths.

**Describe the bug**
Long post titles cause dates to appear in the wrong spot.

**Expected behavior**
Perhaps the maximum width of the titles could be limited, and the date could line up horizontally with the first line of the post title.

**Screenshots**
![anatole_issue](https://user-images.githubusercontent.com/6765756/106013635-e0936f00-6079-11eb-8909-90e6f7f04b73.png)

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version of the Theme 6f804985e4e301afc26e9d4cf26b8f3030d8887a
 - Version of Hugo: `Hugo Static Site Generator v0.80.0-792EF0F4/extended linux/amd64 BuildDate: 2020-12-31T13:46:18Z`

**Additional context**

**Comment by lxndrblz** [comment]
@cwpearson  Thanks for the in-depth description. I'll need to reproduce this and will report back. I am sure this problem can be solved with a bit of CSS.

**Comment by cwpearson** [comment]
I did a quick fix with custom css

```
.list-with-title .listing .listing-post a {
    max-width:90%;
    display: inline-block;
}
```

But this is the most CSS I have ever written :D so there may be a better way

**Comment by lxndrblz** [comment]
@cwpearson  I just came up with the same solution, additionally we could specify the width for `post-time` to let say 10 % and make it allign right. I am currently testing if that would cause any new bugs.

**Comment by cwpearson** [comment]
Thank you very much. [I sponsored this repo, hopefully anyone who stumbles across this issue will be inspired to do the same if you have helped them](https://Ko-fi.com/home/coffeeshop?txid=923fd7d2-4a54-4212-9aac-026d66ad6a5f&mode=public&img=ogiboughtsomeone).

**Comment by lxndrblz** [comment]
@cwpearson Thanks very much. Highly appreciated. Few people realise the amount of time, learning and effort it takes to maintain this. 👍 

Back to your issue. I will push an update tonight. There is still an edge case I want to resolve for the mobile view.
