### ISSUE TITLE
Theme switching does not seem to work on mobile

### ISSUE THREAD

**Issue by shariq1989** [lxndrblz/anatole#130]
This does not bother me too much because I intend on removing the theme switcher and locking in the light theme but I noticed that my site on mobile when switched only switches the drop-down menu.

1. Go to https://themes.gohugo.io/theme/anatole/ on Firefox mobile
2. Click on the dropdown menu
3. Switch the theme
4. Your result should be similar to what I am seeing in the screenshot.

<img src="https://user-images.githubusercontent.com/2559167/106223127-15004b80-619e-11eb-9923-0a9e9935b36a.jpg" alt="drawing" width="200"/>

**Comment by lxndrblz** [comment]
@shariq1989 Thank you for reporting the issue. I couldn't fully reproduce the issue. When I click on the text/icon on FF it would switch, but not if I click besides it (on the blank space). Is that the same for you or does it not switch at all?

**Comment by shariq1989** [comment]
It won't switch if clicked beside, only when the icon is clicked. And it only ever switches the drop-down menu. The issue I brought up is only happening on my mobile browser FF, nowhere else. Working fine in mobile Chrome as well.

**Comment by shariq1989** [comment]
It seems like it is moreso the dark mode on my phone that was forcing the issue. Once I turned that off, the site started functioning as expected.
