### ISSUE TITLE
adding RTL to multilanguage websites

### ISSUE THREAD

**Issue by KourosZanbouri** [lxndrblz/anatole#135]
First of all, Thank you @lxndrblz for this amazing theme...

I'm trying to create a multi-language website (I'm new to the whole Hugo ), Here are some issues :

1-adding multilanguage website ( ie. FA ( Persian-Farsi) & English ( EN ) ) does not change the RTL of posts ( Fa is RTL , the title and content is still LTR)

2-menus need to be RTL too and Align Right ( of course you can change the order of them by changing weights but not aligning right )

3-is there a way to add Persian calendar to posts? ( Jalali - Hijri Shamsi )

**Comment by lxndrblz** [comment]
Hi there,

Thanks for bringing up this interesting issues.

I am aware that the Persian layout is quite different and could technically be realised with changes to the css. 

However, the necessary changes are quite dramatic (it's almost like the changes necessary for the dark theme) and quite labour intensive. Honestly I don't see this coming any time soon. 😔

RTL support is something I can add to the to do list for the future, but If you need an immediate solution than it might be best to look for a different theme such as _Coder_ which comes with a dedicated RTL support.

**Comment by KourosZanbouri** [comment]
thank you for your reply,

I'm looking forward to your next updates regard RTL support ;)
