### ISSUE TITLE
git Dirty

### ISSUE THREAD

**Issue by anthow** [lxndrblz/anatole#137]
Hello, thanks for you very nice theme.

I use your theme for a little personnal page who will be hosted on Netlify.
But when i want to commit my site on Github i have this issue: 

Subproject commit 05841e4ed0ac6f214cd9091ffcf3f9cd1fd3f4f6
Subproject commit 05841e4ed0ac6f214cd9091ffcf3f9cd1fd3f4f6-dirty

for the folder themes/anatole

do you have a solution ? 
thanks !

**Comment by lxndrblz** [comment]
@anthow This error usually happens if you edited files in the submodule (The anatole theme). 

Do you want to keep the changes?

**Comment by anthow** [comment]
@lxndrblz Hello, i just ad a custom.css file on this folder.
Do I have to put it back in another place? 
my css file doesn't work when the folder is put at the root of my site

**Comment by lxndrblz** [comment]
@anthow  You need to place the `custom.css` in your assets directory. I usually create a subdirectory named `css` in there and link it like `customCss = ["css/custom.css", "css/styles.css"]`. It's the assets directory of your site and not the theme.

**Comment by anthow** [comment]
ok ! its working ! 
thank you very much for help
