### ISSUE TITLE
Differences between _index.md and mds within the content folder

### ISSUE THREAD

**Issue by RRMaximiliano** [lxndrblz/anatole#138]
**Describe the bug**

Hi, I want to have a static page as my home page but it seems that there are differences between the _index.md file and, for example, my bio.md style. My website is: https://rrmaximiliano.github.io/

The _index.md has the title capitalized. In contrast the `md`s within the content folder have the title uppercased. The same happens for the hyperlink's colors. Below there are some screenshots of said problem.

- _index.md

![image](https://user-images.githubusercontent.com/7269831/108273191-d9bbc180-7138-11eb-8087-d5c522b218a3.png)

- other page

![image](https://user-images.githubusercontent.com/7269831/108273295-f6f09000-7138-11eb-9f83-80402ce7e9b7.png)

Should this be changed in the `style.css`? Which parameter?  

**Notes**

- I am using the `blogdown` package in R to load the theme, and copying the public folder into my github repository to deploy my website.

**Comment by lxndrblz** [comment]
Hi there,

 

I was able to reproduce the error locally, but I don’t have a solution for it yet.

It seems like the CSS does not apply to the content of the `_index.md` file. I will need to investigate it more in-depth.
