### ISSUE TITLE
Is Google Analytics Functional?

### ISSUE THREAD

**Issue by abraithwaite** [lxndrblz/anatole#139]
Maybe I don't understand how it was implemented, but I don't see an `_internal` directory with the analytics configuration:

https://github.com/lxndrblz/anatole/blob/05841e4ed0ac6f214cd9091ffcf3f9cd1fd3f4f6/layouts/partials/footer.html#L18

Is that a special directory provided by Hugo or something?  I didn't see any changes here which would indicate that it ever got added:

https://github.com/lxndrblz/anatole/commit/ca58d70c3c0b84f753b5e43a0feafc12e4d97141

Thanks!  Love the theme. 👍🏽

**Comment by lxndrblz** [comment]
Hi there,

 

it’s a snippet that comes with Hugo, therefore, there is no need to include it in the theme.

 

Internal Templates | Hugo (gohugo.io) <https://gohugo.io/templates/internal/> 

Best regards,

Alex

**Comment by abraithwaite** [comment]
Thanks, I should have searched first.  I will do more debugging on my end then, as I'm not seeing it initializing correctly.

**Comment by lxndrblz** [comment]
It is usually quite easy. Simply set the `googleAnalytics = "UA-123-45"` param in the `config`.

**Comment by abraithwaite** [comment]
Yep, it was a dumb mistake on my end.  When I went to debug I stupidly assumed I knew more about hugo than I do, and wasn't aware of the internal feature.  Thanks!
