### ISSUE TITLE
Error: Error building site: failed to render pages: render of "page" failed

### ISSUE THREAD

**Issue by Dicky1** [lxndrblz/anatole#142]
After adding theme, I am getting following error.
I have tried with brand new site, without any content, facing the same issue.

➜  quickstart git:(master) ✗ hugo server -D          
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:3:4: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:41:17: executing "_internal/opengraph.html" at <index $siteSeries $name>: error calling index: index of untyped nil

➜  quickstart git:(master) ✗ hugo version   
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z

➜  quickstart git:(master) ✗ cat config.toml 
baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "My Website"
theme = "anatole"

**Comment by lxndrblz** [comment]
@Dicky1 Thanks for bringing this to my attention. The error comes from the Opengraph implementation, which expects a series configured in the `config.toml`. Simply add:

```toml
## Taxanomies for Opengraph
[taxonomies]
  series = "series"
```

I will update the example config accordingly.
