### ISSUE TITLE
Inject JS/CSS into mainpage

### ISSUE THREAD

**Issue by Corfucinas** [lxndrblz/anatole#146]
Hi, I want to create a modal for my profile picture (just add a simple animation)

How can I inject the modal into the main page?

Sorry if the question seems a bit simple...I mainly only do Python

The code will be adapted from here => https://www.w3schools.com/css/tryit.asp?filename=trycss_image_modal_js

In case you want to see a ref.

**Comment by lxndrblz** [comment]
@Corfucinas  You can add these functionalities through custom css files and custom js files. Simply split the example accordingly (CSS into CSS file, JS into JS file). 

If you are specifically after the image-zoom, then you shouldn't need to make any adjustments, as anatole ships with medium-zoom, which produces a similar effect.

**Comment by Corfucinas** [comment]
Thanks for the answer @lxndrblz 

Sorry for my late reply, too busy for my own taste this week.
Could you provide me a code example on Anatole zoom? I didn't seem to come across it.

**Comment by lxndrblz** [comment]
The JavaScript is located in `assets/js/medium-zoom.js`, the css located in `assets/css/style.css`. You should notice it, when you click on an image (it should zoom in and increase). 

The medium-zoom comes as a partial, which is linked in the `footer.html`.

**Comment by Corfucinas** [comment]
Like I mentioned above...I do not have that much experience on anything related to front-end (doing my own website as an exercise to develop those skills).

https://corfucinas.github.io/

I can't seem to get that functionality working on my website, should I copy `assets/js/medium-zoom.js` to my project folder?

Also, seems the image on https://corfucinas.github.io/resume/resume.html is getting a complaint from  lighthouse avoid having to fetch the css and the image, seems Hugo does offer a way to cache things (https://gohugo.io/functions/partialcached/) you probably know, but just sharing since it can help someone else that reads this.

How can I implement that functionality? Most of my site will be static, so I doesn't make sense to fetch everything on every refresh

**Comment by lxndrblz** [comment]
@Corfucinas No need to copy anything - it should work by default on any post. Unfortunately, when I go to your resume page, I get a lot  of 404:

![image](https://user-images.githubusercontent.com/12200062/110795031-458fd680-826e-11eb-93d7-b485bdc76256.png)

I, therefore, can't test the medium zoom. Could you please provide me with a link that works?

Regarding your resume: Is that done using the anatole theme? To me it looked like a separate static html template.
If it's an anatole related error, would you mind providng me a screenshot of the error you are seeing in the lighthouse console?
