### ISSUE TITLE
Support for google analytics gtag

### ISSUE THREAD

**Issue by Xen-Echo** [lxndrblz/anatole#148]
Hi, I'd like to add support for the google analytics gtag.

As far as I'm aware Hugo doesn't yet support the newer gtag method for analytics and Google actively discourages generating older UA style properties.

I've implemented this on my own site and wondering if it's something worth adding to the theme? I'm happy to do it or make any changes:

New Partial: `google-analytics-gtag-async.html`

```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ .Site.Params.gtagId }}"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '{{ .Site.Params.gtagId }}');
</script>
```

Modify: `footer.html`

```
{{- if and (hugo.IsProduction) (.Site.Params.gtagId) -}}
    {{ partial "google-analytics-gtag-async.html" . }}
{{- end -}}
```

Then the `gtagId = "G-XXXXXXXXXX"` can be added to the `[params]` block of the config to get it to work, I've made use of the `isProduction` function so I don't get my development traffic logged.

Cheers.

**Comment by lxndrblz** [comment]
@Xen-Echo I am sure that could be a valuable contribution. Would you mind opening up a separate PR for it?

**Comment by Xen-Echo** [comment]
@lxndrblz Yes, no worries.
