### ISSUE TITLE
Social icons not showing

### ISSUE THREAD

**Issue by pythrick** [lxndrblz/anatole#15]
https://themes.gohugo.io/theme/anatole/

**Comment by lxndrblz** [comment]
Hi there,

Would you mind sharing a screenshot of what it looks like on your device?

The social icons appear perfectly fine on all of my devices. Please also include the information about the Browser/platform. This could help me to track down the issue.

Alex

**Comment by pythrick** [comment]
I've just found the issue, it was in my browser extension: Adblock Plus. I can't figure out why it happens, but when I deactivate the extension the social links shows up again. I'm using Google Chrome btw. Maybe it should not treated as a bug, so, I'm sorry about creating this issue.

**Comment by lxndrblz** [comment]
Thanks for the clarification. I will go ahead and close the issue, as this doesn't seem to be an issue realized to the theme itself. Other adblocker such ublock dont seem to have any issues.
