### ISSUE TITLE
post tag and category link to 404 page

### ISSUE THREAD

**Issue by xiangli2pro** [lxndrblz/anatole#151]
Hello there, 

Thank you for the beautiful theme. I have some problems with the 'tag' and 'category' features of the post, I appreciate it if you can help me with it.

In the demo, 'tag' and 'category' of each post are linked to the 'posts' page. However, when I run the theme on my local server, the 'tag' and 'category' point to the 404 page.

Here is what I did, in the terminal:
hugo new site quickstart -> cd quickstart -> git init -> git submodule add https://github.com/lxndrblz/anatole.git themes/anatole -> echo theme = \"anatole\" >> config.toml
Then I copy the config.toml and content folder from the path quickstart/themes/anatole/exampleSite/ to the main directory quickstart/, then launch the website in the local server. 

Could you please tell me how to make the 'tag' and 'category' direct to the 'posts' page? Thank you,

I am using 
macOS Catalina, 
safari browser, 
latest version of the theme 
hugo v0.81.0+extended darwin/amd64 BuildDate=unknown

**Comment by lxndrblz** [comment]
@xiangli2pro  Thanks for your description. I was able to reproduce the error locally and will report back once I have a solution.

**Comment by lxndrblz** [comment]
Hi there, please try again using the latest version. The problem is if a taxonomy is defined in the `config.toml`, Hugo was expecting that categories and tags are also defined there. It should be working now.

**Comment by amaothree** [comment]
Hi lxndrblz, I have to report after this update my post tag page be 404 now :(

I build a multi-language blog. Before this update I can visit my Chinese posts and English posts in _https://amao.run/zh/posts_ and _https://amao.run/en/posts_ . Now they are 404. And I also found if I directly visit the link _https://amao.run/posts/_ , I can visit the default language posts page (Chinese in my blog) normally.

You can check my config file and my repo at here: https://github.com/amaothree/amaothree.github.io
My blog here: https://amao.run/

**Comment by amaothree** [comment]
> Hi there, please try again using the latest version. The problem is if a taxonomy is defined in the `config.toml`, Hugo was expecting that categories and tags are also defined there. It should be working now.

Hi @lxndrblz , I have to report after this update my post tag page be 404 now :(

I build a multi-language blog. Before this update I can visit my Chinese posts and English posts in https://amao.run/zh/posts and https://amao.run/en/posts . Now they are 404. And I also found if I directly visit the link https://amao.run/posts/ , I can visit the default language posts page (Chinese in my blog) normally.

You can check my config file and my repo at here: https://github.com/amaothree/amaothree.github.io
My blog here: https://amao.run/

Windows 20H2
Theme version: commit 76d1d71
hugo v0.81.0-59D15C97 windows/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio

**Comment by lxndrblz** [comment]
I'll have a look and report back, but the problem seems different from the one @xiangli2pro had.

**Comment by xiangli2pro** [comment]
Thank you! That works for me. 

I have two follow up questions. If necessary I can open up new issues for them.

1. I update the theme using the command `git submodule update --remote --merge` in the terminal, under the path '/quickstart/' (use the project example mentioned in my first question). However, I did not detect any changes on '/quickstart/themes/anatole/'. So I had to start a new site with the Anatole theme and copied the 'new site/themes/anatole/' to  '/quickstart/themes/anatole/'.

Should I execute the update command in different file path?  Or use different command?

2. How can I add `read more` feature on each post listed on the home page?
I noticed in the style.css, there is this class `.read_more`. Is this the one to use? How can I set it up?

Thank you,

**Comment by lxndrblz** [comment]
@amaothree I've moved your message to a separate issue #155.

**Comment by lxndrblz** [comment]
@xiangli2pro Regarding 1) That's the correct approach. I usually run the git submodule update in the directory where my .git file is. You should see a command output with the files and number of lines which have changed since the last version. Did you see that?

Regarding 2) The read more class is not used in this theme and I believe the original theme by Cai Cai didn't have that ability either. The current approach is to use .summary to define a custom blog summary.

**Comment by xiangli2pro** [comment]
Thank you for the information!
