### ISSUE TITLE
Rendering matrix in katex

### ISSUE THREAD

**Issue by egealpay** [lxndrblz/anatole#152]
**Describe the bug**
I cannot render any matrix in katex

**To Reproduce**
1. Create a markdown file which uses katex for math.
2. Copy any matrix in https://katex.org/docs/supported.html
3. Paste matrix formula in markdown as block formula

**Expected behavior**
<img width="89" alt="Screen Shot 2021-03-12 at 19 43 12" src="https://user-images.githubusercontent.com/25003254/110970839-304ca200-836b-11eb-8aaa-6495fe9f2f01.png">

**Screenshots**
<img width="213" alt="Screen Shot 2021-03-12 at 19 42 44" src="https://user-images.githubusercontent.com/25003254/110970763-2165ef80-836b-11eb-84a2-1cc130cfc2c3.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Brave
 - Version of the Theme: 0.4
 - Version of Hugo: 0.80

**Comment by lxndrblz** [comment]
@egealpay  Thanks for reporting this.

I think the issue has to do with escaping the double \\ in katex. If I try to run the following snippet I am getting a nicely formatted math function:

`
$$
\\begin{bmatrix}
   a & b
\\end{bmatrix}
$$
`
However, once there is a new line within the matrix it breaks. For example, I'd tried the following with mathjax enabled, and it didn't have any issues (note that you will have to escape the backslashes):

`
$$
\\begin{bmatrix}
   a & b \\\\
   c & d
\\end{bmatrix}
$$
`
![image](https://user-images.githubusercontent.com/12200062/110973698-78f96080-8355-11eb-9641-37ae4d706b1f.png)

Do you want to use katex specifically, or id mathjax also sufficient? In the former case, I would do a bit more digging, why it doesn't escape correctly.

**Comment by egealpay** [comment]
Thanks a lot 👍
