### ISSUE TITLE
Meta description is always the same

### ISSUE THREAD

**Issue by Xen-Echo** [lxndrblz/anatole#153]
Currently, the meta description tag in the page head is always the description set in the config:

```html
<meta name="description" content="{{ .Site.Params.description }}">
```

This results in all the pages having the same meta description, Google recommends they be differentiated from one another: 
https://developers.google.com/search/docs/advanced/appearance/good-titles-snippets#meta-descriptions

I've got a proposal I can submit a PR for that uses the "description" Front Matter of a page or falls back to what it currently is if it's not set on the page:

```html
<meta name="description" content="{{ if .Params.description }}{{ .Params.description }}{{ else }}{{ .Site.Params.description }}{{ end }}">
```

**Comment by lxndrblz** [comment]
Another spot-on idea. Would you mind making a separate PR for it?
