### ISSUE TITLE
Posts not showing up on multi-language blog (Posts page)

### ISSUE THREAD

**Issue by lxndrblz** [lxndrblz/anatole#155]
> Hi there, please try again using the latest version. The problem is if a taxonomy is defined in the `config.toml`, Hugo was expecting that categories and tags are also defined there. It should be working now.

Hi @lxndrblz , I have to report after this update my post tag page be 404 now :(

I build a multi-language blog. Before this update I can visit my Chinese posts and English posts in https://amao.run/zh/posts and https://amao.run/en/posts . Now they are 404. And I also found if I directly visit the link https://amao.run/posts/ , I can visit the default language posts page (Chinese in my blog) normally, it should not be.

You can check my config file and my repo at here: https://github.com/amaothree/amaothree.github.io
My blog here: https://amao.run/

Windows 20H2
Theme version: commit 76d1d71
hugo v0.81.0-59D15C97 windows/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio

_Originally posted by @amaothree in https://github.com/lxndrblz/anatole/issues/151#issuecomment-797826198_

**Comment by lxndrblz** [comment]
@amaothree  Could you please confirm that `http://localhost:1313/zh/posts/` worked for you before? I am currently trying to debug your site.  At least I am seeing the same error locally as on your website.

**Comment by lxndrblz** [comment]
It seems like it is currently located under `http://localhost:1313/posts/`. I will check if its possible to show it under the zh directory again.

**Comment by lxndrblz** [comment]
@amaothree add the following two lines to your `config.toml` and you should be good to go.

defaultContentLanguageInSubdir = true

[params]
mainSections = ["posts"]

Please let me know, if the issue still persists.

Btw. your english post didn't show up because it was a draft. :)

**Comment by amaothree** [comment]
Thanks your support. These configs fix the problem !
