### ISSUE TITLE
What's JQuery used for?

### ISSUE THREAD

**Issue by Xen-Echo** [lxndrblz/anatole#157]
Hi, Could you point me to what's actually using JQuery in the theme? It pulls in JQuery, JQuery Migrate, and JQuery Appear but I'm struggling to actually find anything that uses it.

Cheers.

**Comment by lxndrblz** [comment]
@Xen-Echo  Good question! It should no be longer necessary to load the three scripts you are referring to, as everything else (Hamburger Menu, Theme Switcher and Medium Zoom) are implemented in vanilla JavaScript.

**Comment by Xen-Echo** [comment]
Awesome I guess the question is: should I remove them? Could shave some loading time and the pages aren't bloated with unused scripts!

**Comment by lxndrblz** [comment]
@Xen-Echo You were a bit faster commenting than I could push the update. I've removed them now, as it will help with the load times, maintainability and security.

**Comment by Xen-Echo** [comment]
@lxndrblz Awesome thanks for that!
