### ISSUE TITLE
utterances comments not showing up

### ISSUE THREAD

**Issue by xiangli2pro** [lxndrblz/anatole#158]
Hello there,

I have been trying to set up the utterances comments for each post, I have downloaded the utterances app in the website repo and set the parameters in config.toml as below, but there is no comments showing up in local server or online web.

```
[params.utterances]
repo = "xiangli2pro/xiangli2pro.github.io"
issueTerm = "pathname"
theme= "preferred-color-scheme"
crossorigin="anonymous"
```

I only modified the `config.toml`,  added `customer.css`, and added .md files in the content folder.  I updated the anatole theme yesterday.

I have also tried the disque, but it did not work either. I have been searching around but could not figure out, could you please tell me how to fix this?  Thank you,

**Comment by Xen-Echo** [comment]
Might be wrong here but I ran into a similar block setting up comments on my site, comments only appear on "post" types and I have my content structured slightly differently. 

Adding 

```
type: post
```

to the markdown files [Font Matter](https://gohugo.io/content-management/front-matter/) fixed it for me.

**Comment by lxndrblz** [comment]
@Xen-Echo is basically correct. The comments are only loaded for post types and if comments are not disabled globaly. Let me know if that fixed your issue, else I will have a look at your config/files.

**Comment by xiangli2pro** [comment]
Thank you all! That works for me!

After I add `type: post` in `.md` file, the post has comment box now, but the post disappear from the home page. I fix it by adding `"post"` into parameter `mainSections` in the `config.toml`.
