### ISSUE TITLE
add Read More feature

### ISSUE THREAD

**Issue by xiangli2pro** [lxndrblz/anatole#159]
Hello there, 

I followed the idea from this link https://discourse.gohugo.io/t/read-more-links-in-paginated-posts/9163/2, and I was able to add the `read more` link on post listed on home page. I add the below code in anatole/layouts/index.html between code chunk 'post-content' and 'post-footer'.

```html
<!--  <div class="post-content"> <div>  -->

{{- if .Truncated -}}
  <a href='{{ .RelPermalink }}'>&hellip; Read more</a>
{{- end -}}

<!--  <div class="post-footer"> <div> -->
```

**Comment by lxndrblz** [comment]
@xiangli2pro Would you mind opening a PR so we can track this change?

**Comment by lxndrblz** [comment]
Question regarding read-more functionality came up in issue #151

**Comment by xiangli2pro** [comment]
Sure, I will open a separate PR. Thanks.
