### ISSUE TITLE
Multi-line slogans

### ISSUE THREAD

**Issue by dgrevink** [lxndrblz/anatole#161]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have multi-lined slogans on the sidebar.

**Describe the solution you'd like**
I would like to be able to specify a string with newlines in config.toml for the description field and when Hugo generates it have the sidebar display it properly.

I have a pull-request ready for this.

**Comment by lxndrblz** [comment]
@dgrevink Feel free to send me a PR and I will review it. :)
