### ISSUE TITLE
Partials Footer

### ISSUE THREAD

**Issue by snowfoxboots** [lxndrblz/anatole#162]
Hello. I get an error when trying to build on Netlify related to the partials/footer.html:
<hugo>: can't evaluate field IsProduction in type interface {}
Is there something I'm missing? I am new at working with Hugo.. Thanks.

**Comment by lxndrblz** [comment]
@snowfoxboots Would you mind sharing what Hugo version you are using?

**Comment by snowfoxboots** [comment]
hugo v0.81.0+extended darwin/amd64

**Comment by Xen-Echo** [comment]
@lxndrblz Here's the version I use as I included that line a part of the GA4 analytics request: 

hugo v0.81.0-59D15C97 windows/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio

Though I don't use Netlify

**Comment by lxndrblz** [comment]
I imagine it's caused by the following if clause:
`
{{- if and (hugo.IsProduction) (.Site.Params.gtagId) -}}
`
Though, that shouldn't be an issue. I'll do some research and report back.

@snowfoxboots  Would you mind sharing the full error messaging you are seeing?

**Comment by lxndrblz** [comment]
@snowfoxboots  Could you please also share your `netlify.toml`?

**Comment by snowfoxboots** [comment]
Ah this is my mistake, I didn't update the newest version on the netlify.toml file. It does work.

**Comment by lxndrblz** [comment]
@snowfoxboots That was a quick fix. Please let me know, if you are still running into another issue.
