### ISSUE TITLE
[FR] Smoother dark theme

### ISSUE THREAD

**Issue by ericswpark** [lxndrblz/anatole#173]
It would be great if the current dark mode implementation can be changed so that it follows the system (Windows/macOS) theme set in settings. This way, the website automatically follows the system theme as it changes (for example, on macOS the system theme changes depending on sunrise/sunset).

For reference, please see: https://web.dev/prefers-color-scheme/#the-prefers-color-scheme-media-query and https://web.dev/prefers-color-scheme/#smooth-transitions-between-modes

**Comment by lxndrblz** [comment]
@ericswpark Regarding the automatic switching: That's already implemented if you check the [anatole-theme-switcher.js](https://github.com/lxndrblz/anatole/blob/master/assets/js/anatole-theme-switcher.js). However, it only checks upon first visit (when there are no settings set). Do you want the system settings always have priority over the last set setting?

We had the transition in the early days and it resulted in weird side effects on some browsers, such as flashing. If you really want this transition, then I would encourage you to use a custom css for that.

**Comment by ericswpark** [comment]
Hmm, I got this idea from sites that transition as the system changes from light to dark (or vice versa). I think the script should work as-is, but continuously check instead of checking once and transition as the system transitions. And then maybe we could disable the transition if the user has used the toggle before to force a specific mode.

The flashing thing sounds strange; does this issue occur on modern browsers?

**Comment by lxndrblz** [comment]
@ericswpark If you want, we could work on it in a separate PR.

I think the continuous check would be a decent idea or at least on every reload.
Yes, I believe it was on iOS.

**Comment by lxndrblz** [comment]
The original issue was discussed in issue #21

**Comment by ericswpark** [comment]
@lxndrblz I just updated my website to the latest commit on master (without the PR added in #167) and for some reason I'm unable to get the automatic switching to work. I tried toggling the system preference a couple of times but the website only picks up the change after a refresh. (Localstorage was cleared out before testing)

For reference, here's my website next to an example site (clien.net) that supports this type of switching:

https://user-images.githubusercontent.com/13326074/113971007-df996d80-9872-11eb-9adb-e9e1d1991bdc.mp4

I'll try changing it if I have time later but the site on the left is the effect I'm going for.

**Comment by lxndrblz** [comment]
@ericswpark It is not yet in the master branch. Before merging it I still wanted to get your opinion. Please check out the dark mode branch.

**Comment by ericswpark** [comment]
@lxndrblz tried:
 - checking out `darkmode` branch
 - checking out `master` and merging `darkmode` on top

For both cases I wiped local storage, but the auto switcher still doesn't kick in for some reason. The color changes if I refresh the page.

As for the `darkmode` branch it looks nice! The color might be a bit too dark I think.

I noticed the transition implemented doesn't fade out the background from white to black. Is that intentional?

**Comment by ericswpark** [comment]
@lxndrblz can you check out https://github.com/ericswpark/anatole/commit/aa3d70f999c541c92bdbdfac9e77318821ac7626? It's a dirty patch to make the auto switching work.

I copied the CSS file to two light/dark.css files and then loaded them both with the CSS media query set. Then the browser handles the transition automatically when the system theme changes. Unfortunately, I had to patch out the entire theme switching script, so it breaks the switching button, but at least the auto switcher works now.

I think for my site I'll just disable the switcher completely and have it follow the system theme. The transition looks great when the system theme switches from light to dark :D

**Comment by lxndrblz** [comment]
@ericswpark  Thats one of the things I noticed too. The autoswitcher and switch don't play along nicely. I'll  have a look at your patch and see if I could merge into the PR somehow.

**Comment by lxndrblz** [comment]
@ericswpark I wanted to report back on this issue. I'd tried to integrate a smooth transition between the modes. While I got it working, it was incredibly unevenly occurring across the site. Some portions would fade faster than others. I, therefore, decided to not implement this feature. What I added, however, is a listener for detecting the system preference change. 

As soon as my dark mode branch is ready, it will also be available in the master branch.

**Comment by ericswpark** [comment]
> @ericswpark I wanted to report back on this issue. I'd tried to integrate a smooth transition between the modes. While I got it working, it was incredibly unevenly occurring across the site. Some portions would fade faster than others. I, therefore, decided to not implement this feature. What I added, however, is a listener for detecting the system preference change.

That's fine, I think we had a bit of a miscommunication. The "transition" I was talking about was macOS/Firefox smoothly transitioning between light mode and dark mode, based on the prefers-color-scheme attribute.

I'll check out the latest commit and see if it still works. Thanks!
