### ISSUE TITLE
math not rendered properly

### ISSUE THREAD

**Issue by xiangli2pro** [lxndrblz/anatole#174]
Hello there,

I was trying to render the below math equation but failed, I think I am using the Katex supported functions and I can render other math symbols, could you please help me with the issue? Thank you.

```
$$
x = ( \underbrace{0...0}_{N_1}, \underbrace{0...0}_{N_2} )^T
$$
```

The correct version should look like this.
<img width="166" alt="Screen Shot 2021-04-01 at 10 17 42 PM" src="https://user-images.githubusercontent.com/78754416/113373228-63fe6480-9338-11eb-941d-5c2e68482757.png">

May I ask how can I check the theme version applied on my website? Is there any terminal commands I can use? Thank you.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser: safari
 - Version of Hugo: hugo v0.81.0+extended

**Comment by lxndrblz** [comment]
@xiangli2pro Thanks for reporting this. I was able to reproduce the problem but have no solution (yet). I will do a bit more digging. What I noticed so far is that the problem only seems to occur if there is more than one N.

**Comment by xiangli2pro** [comment]
Hello there,

I think I have figured out the issue. The equation can be rendered after I replace `_` by `\_` after `\underbrace{}`. Now the equation below can be rendered successfully. 
``` 
$$
x = ( \underbrace{0...0}\_{N_1}, \underbrace{0...0}\_{N_2} )^T
$$
```

I got the idea from the support post [here](https://discourse.gohugo.io/t/rendering-math-symbols-with-katex-in-hugo/4146).

**Comment by lxndrblz** [comment]
Great @xiangli2pro to hear you were able to resolve the issue and thanks for sharing the solution with us.  👍
