### ISSUE TITLE
Unable to deploy to S3

### ISSUE THREAD

**Issue by plutov** [lxndrblz/anatole#176]
I used the following config to deploy my blog before:

```
[deployment]

[[deployment.targets]]
name = "s3"
URL = "s3://pliutau.com?region=us-east-1"
cloudFrontDistributionID = "..."
```

Now I see the following error when deploying:
```
ERROR 2021/04/07 14:56:55 render of "taxonomy" failed: execute of template failed: template: _default/list.html:16:4: executing "_default/list.html" at <partial "footer.html" .>: error calling partial: "/home/runner/work/pliutau.com/pliutau.com/themes/anatole/layouts/partials/footer.html:4:12": execute of template failed: template: partials/footer.html:4:12: executing "partials/footer.html" at <hugo>: can't evaluate field IsProduction in type interface {}
```

**To Reproduce**
1. Apply the above config
2. Deploy using `hugo -v deploy --maxDeletes -1`

**Expected behavior**

No errors should be returned.

**Desktop (please complete the following information):**
 - OSX
 - Latest version of theme
 - Hugo v0.79.

**Comment by lxndrblz** [comment]
@plutov Thanks for bringing this issue up. The problem seems to do with the `IsProduction` check. According to the [documentation](https://gohugo.io/getting-started/configuration/) Hugo will set the environment to production if the hugo command is used so that should be good.

Out of curiosity, are you able to build the site without the deploy command?

**Comment by lxndrblz** [comment]
Based on your latest [commit](https://github.com/plutov/pliutau.com/commit/eddc89049944348b11d63cd774662656d9a1fcfe#diff-87ee5504a3e25ac558b343724c905f2f7949e8cec3d92b9c4300bb922afa164f) it appears as the GitHub action succeeded. Were you able to get it resolved?

**Comment by plutov** [comment]
Exactly, I was aable to figure it out. The issue can be closed! The theme is cool and Live as you can see :)
