### ISSUE TITLE
Thumbnail size and cropping

### ISSUE THREAD

**Issue by nicholascarey** [lxndrblz/anatole#177]
It would be nice to be able control the size of the thumbnails as they appear at the top of posts, and also the size and cropping as they appear in the post list on the home page. 

Maybe there is a way of doing this I haven't worked out yet?

**Comment by lxndrblz** [comment]
@nicholascarey No you did not miss anything. The images right now have to be cropped and scaled manually right now.

Image processing is something I don't prioritise for static sites as I think it is not a major issue. It would also be hard to choose the correct section without a visual editor. If you have a working code to address this feature request, then feel free to open a PR.

**Comment by nicholascarey** [comment]
Ok, no worries!
