### ISSUE TITLE
Lighthouse report: Performance concerns

### ISSUE THREAD

**Issue by msfjarvis** [lxndrblz/anatole#18]
Running Lighthouse on the site points out a few problems, which I'm splitting across separate issues based on category to make them easier to triage.

For performs, the following issues were reported:

- Eliminate render-blocking resources

Flagged due to https://github.com/lxndrblz/anatole/blob/master/layouts/partials/head.html#L13

- Ensure text remains visible during webfont load

Flagged again by FontAwesome but not sure we can do anything about it.

[View the report](https://bin.msfjarvis.dev/~5ec7bcd61de3ad00122e4ef6/raw?ctype=text/html)

**Comment by lxndrblz** [comment]
I got a perfect score, despite those two recommendations. I'll check if we can resolve this, but I doubt there is an easy solution (especially not for the later issue).
