### ISSUE TITLE
Side Bar size option

### ISSUE THREAD

**Issue by a0m0rajab** [lxndrblz/anatole#180]
**Side Bar option in params**
Is there any possibility to set the sidebar size from the params of Hugo? this way the Theme user will be able to choose if the side bar would be only 40% or less! the thing is that it may offer more screen usage and have a bit clearer theme.

**Comment by lxndrblz** [comment]
I have some code locally already for addressing this enhancement: 

![image](https://user-images.githubusercontent.com/12200062/115446758-93a1dd80-a20f-11eb-93f6-04aecedc221f.png)

Basically, it allows to set the ratio (0.7) via the config. I only need to fix an issue with ultrawide screens, where the output is distorted.

**Comment by a0m0rajab** [comment]
Tha'ts great to know! 
For me I was thinking that to give the ability to change the full ration and play around with it, some users may want to set it for 0.5.

**Comment by lxndrblz** [comment]
Yes, that is possible basically any meaningful value between 0 and 1 will do (0.5, 0.6, 0.8 etc.).

**Comment by AyrtonRicardo** [comment]
@lxndrblz is this going to be release and documented or am I missing the docs related to this issue?

**Comment by lxndrblz** [comment]
@AyrtonRicardo You didn't miss anything. It is still in the making. I hope to finish it within the next few days.

**Comment by iamthefrogy** [comment]
I changed it to 0.8 but it only worked on home page but not any other pages.

I made below changes.

<img width="1139" alt="image" src="https://github.com/user-attachments/assets/e7b36a36-38b6-41a1-a280-c3cefa3b436e" />
