### ISSUE TITLE
postSectionName = "blog" does nothing

### ISSUE THREAD

**Issue by brinkabeler** [lxndrblz/anatole#181]
**Describe the bug**
I want to have my post section to be named "blog" and therefore set postSectionName = "blog" under [params]. All that does is to redirect links from /blog/ to /post/.

This happens when I build locally or in github pages.

**To Reproduce**
1. Go to https://brinkabeler.github.io/
2. Click on Blog
3. arrive at https://brinkabeler.github.io/post/ where all blog posts are also prefixed by /post/

**Expected behavior**
When opening a link to https://brinkabeler.github.io/blog/ that is where I expect to arrive.

**Additional context**
Config file here: https://github.com/brinkabeler/brinkabeler.github.io/blob/main/config.toml

**Comment by lxndrblz** [comment]
@brinkabeler  Hello Martin, you were on the right track. Only thing you missed, is renaming your post folder (inside of content) to blog. Once, that is done all posts will show up under your blog and will be linked accordingly.

![image](https://user-images.githubusercontent.com/12200062/115404982-bb7c4b80-a1e5-11eb-959c-8034ea826c02.png)


Hope that helps.

**Comment by brinkabeler** [comment]
Great, thank you! It may be a good idea to document that in the readme for the next person ;)

**Comment by brinkabeler** [comment]
Spoke too soon. This works on my machine, but not when I build on github, for some reason...

**Comment by brinkabeler** [comment]
Apparently it took some time and now works... nevermind, I'll see myself out.
