### ISSUE TITLE
Formatting is different in bullet lists than other body text

### ISSUE THREAD

**Issue by kstrauser** [lxndrblz/anatole#187]
**Describe the bug**
Lists of bulleted items are more tightly spaced, and use a slightly larger font, than other text.

**To Reproduce**
1. Go to https://honeypot.net/post/review-hook-by-cogsci/ for an example.

**Expected behavior**
Bullet lists should have the same line-height and font size as other text.

**Screenshots**

The ul>li elements have the default dense line height and Verdana 15px text. The other text has the 1.9em line height with Verdana 14px text.
<img width="763" alt="Screen Shot 2021-04-27 at 4 30 38 PM" src="https://user-images.githubusercontent.com/295674/116324943-eaf6ff00-a775-11eb-99dd-4de94a4c6fd0.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.3
 - Browser: Safari and Chrome
 - Version of the Theme: commit 2003b9b (from 2021-04-07)
 - Version of Hugo (run a `hugo version` if unsure): v0.82.1

**Comment by lxndrblz** [comment]
@kstrauser  You are completely right. We are missing the following css styling for the ul of post-content.

```css
line-height: 1.9em;
font-weight: 400;
font-size: 14px;
```

**Comment by kstrauser** [comment]
Beautiful. Thanks, @lxndrblz!

**Comment by kstrauser** [comment]
To follow up, this looks _so_ much nicer now. Thanks again!

<img width="759" alt="Screen Shot 2021-04-28 at 11 08 51 AM" src="https://user-images.githubusercontent.com/295674/116452057-234c1b00-a812-11eb-9775-0f27854aaef8.png">
