### ISSUE TITLE
exampleSite - Socials only work with [[params.socialIcons]] set if using config.toml only

### ISSUE THREAD

**Issue by jbarnes** [lxndrblz/anatole#188]
**Social icons would only load if config.toml has [[params.socialIcons]] set if using config.toml only**

**Warning** - I'm very green with Hugo, 

I directly took the **exampleSite** `[[socialIcons]]` examples from the `params.toml` and placed it directly into my singular `config.toml` I only found out I needed to set `[[params.socialIcons]]` in the `config.toml` to get them to work checking another user of your themes code base.

I'm assuming the example site is reading in the `params.toml` file as a collection and this does away with the need for `[[params.` prefix where `[[socialIcons]]` is being used.

So not a bug per se but perhaps some additional documentation around this may be helpful for future users.

Great theme.

**Comment by lxndrblz** [comment]
@jbarnes Thanks for the feedback. It is true, that if the separate files are used then it is possible to omit the params prefix, but not for a single config file. I've just realised the readme doesn't state anything about social icons right now. I think I will include a separate paragraph that addresses this issue. If you have any suggestions, feel free to open a PR.

**Comment by jbarnes** [comment]
Pull Request raised to update readme - https://github.com/lxndrblz/anatole/pull/189
