### ISSUE TITLE
[QUESTION] Missing css and medium-zoom js

### ISSUE THREAD

**Issue by AyrtonRicardo** [lxndrblz/anatole#195]
First of all, thanks for the template it's really clean, beautiful and easily implementable.
Recently I've added this template to my personal website, it's still under construction but I've faced missing CSS and JS when I added CloudFlare to proxy my website.

For reference: https://ayrtonricardo.me
--- the solutions are already applied, so you wont be able to see at the moment the errors in my page, but I can make them visible.

### Problem
Css and Js blocked because Integrity mismatch.

### Reason
Cloudflare when caching your assets, it does minify your files and change it's content as well.
Examples:
1. [style.css#L521](https://github.com/lxndrblz/anatole/blob/master/assets/css/style.css#L521): It changes the color from `black` to `#000`. This is correct from css perspective, but it makes the integrity broken because the hash was generated using `black` and not `#000` in its value.
2. [medium-zoom.js#L1](https://github.com/lxndrblz/anatole/blob/master/assets/js/medium-zoom.js#L1): here it simply removes the space in the commented section. Again, this is totally fine, but it also crashes integrity.

### Solution
You have 2 options:
1. Deactivate `Auto Minify` for the whole website in your firebase configuration for `css` and `javascript` (worked in my case) -- do Minification yourself.
2. Deactivate `Auto Minify` using [`Page Rules`](https://support.cloudflare.com/hc/en-us/articles/218411427-Is-there-a-tutorial-for-Page-Rules-#h_38Gq7mduJiXIjpVLxp3q19) (this did not work in my case, but it can work in yours).

### Question /  Reason to open the issue
Since none of those issues above are really related to the library, my concern is:
1. Does it make sense to document this somewhere in the library? If so, where?(I can do the pr with  documentation).
2. Does it makes sense to change the `black` color to `#000000` and remove spacing in the medium-zoom.js file? (I can also do the pr if it makes sense)
3. Since this took me a while to realise it was a Cloudflare issue, this may be beneficial to others.

**Comment by lxndrblz** [comment]
@AyrtonRicardo Thanks for the in-depth explanation of the problem you had been facing using the theme together with Cloudflare. I'd prefer option 2, because else it will come up over and over again. 

Would you mind opening a PR, with the necessary changes?

Thanks.

**Comment by AyrtonRicardo** [comment]
@lxndrblz sure, I can do the PR modifying the necessary files.

**Comment by AyrtonRicardo** [comment]
Here the PR: https://github.com/lxndrblz/anatole/pull/197
Once again, thanks for quickly replying :)
