### ISSUE TITLE
For German legal reasons, I need a copyright tag at the bottom of the mobile view

### ISSUE THREAD

**Issue by brinkabeler** [lxndrblz/anatole#199]
**Is your feature request related to a problem? Please describe.**
In Gemany, every commercial website needs link to imprint and data protection declaration on every page. [I edited sidebar.html](https://github.com/brinkabeler/brinkabeler.github.io/blob/main/themes/anatole/layouts/partials/sidebar.html) in the theme folder to provide this on desktop view, but I am at a loss at how to display it on phone views.

**Describe the solution you'd like**
I would like some placeholder I can add the required link to in order for it to show at the bottom of every page in every view. Ideally without modifing the theme files.

I tried adding the link into the copyright param in the config file, but was unsuccessful.

**Comment by lxndrblz** [comment]
@brinkabeler Thanks for bringing this to my attention. It's true that the footer is currently not displayed on mobile devices, as it currently lacks the appropriate CSS styling. Indeed, it's currently overlayed by the menu.

I will have a look and report back, how we could get the imprint/Impressum/copyright to stay at the bottom of the page.
