### ISSUE TITLE
Home page issue

### ISSUE THREAD

**Issue by adamj-codethink** [lxndrblz/anatole#2]
Hi there,

loving this theme, thanks for the work!

I'm having an issue where i have a home defined:

[[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

I also have an empty index.md file

However the index.html layout is not loading?

I'd like a home page that shows the most recent blog posts.

Any help on how to fix this would be appreciated

**Comment by adamj-codethink** [comment]
Hi just an update my website is hosted here: https://adamjones.website/

I would like my "About" page to appear automatically when the websites starts, but if i create a index.md and add the markdown from my about page, the site navigation fails?

**Comment by adamj-codethink** [comment]
Hey,

A quick update.

Setting `type: post` on my posts fixed this issue.

The index page now appears correctly listing  my latest blog posts.

I'd still be interested to know if i could remove that and just have a satic text page as the default root page though.

Thanks

**Comment by lxndrblz** [comment]
Hi Adam,

anatole comes with a custom archtype called `post`. If you create a new post by issuing the following command 'hugo new post\foo.md' it will be of type post.

Do I understand you correctly, that you want to use another site other than the `index.html` as your homepage? (Like your about site)
