### ISSUE TITLE
Current item highlighting in navbar is error-prone

### ISSUE THREAD

**Issue by msfjarvis** [lxndrblz/anatole#20]
In the example site, when you select the `About` tab it will not be underlined in the manner `Home` and `Posts` is. I checked the generated HTML and can confirm the Hugo trick used to set `class="current"` seems to not work on standalone pages, as can be reproduced on my staging site at [https://staging.msfjarvis.dev](https://staging.msfjarvis.dev) where all nav items except `Posts` are standalone pages.

**Comment by lxndrblz** [comment]
Hello Harsh, I was able to reproduce the issue and added my changes to a separate branch.
Would you mind verifying if this branch also resolves your issues on your staging site?

**Comment by msfjarvis** [comment]
> Hello Harsh, I was able to reproduce the issue and added my changes to a separate branch.
> Would you mind verifying if this branch also resolves your issues on your staging site?

On it!

**Comment by msfjarvis** [comment]
I don't see any changes in https://github.com/lxndrblz/anatole/commits/buggy-menu, is the branch not fully pushed?

**Comment by lxndrblz** [comment]
My bad. Try again. :)

**Comment by msfjarvis** [comment]
> My bad. Try again. :)

Still doesn't seem to work for the `About` menu item, other two are working. Maybe this is a configuration issue on my site? The source is here if you wanna investigate: https://github.com/msfjarvis/msfjarvis.dev/tree/staging

**Comment by lxndrblz** [comment]
I'll check it out.

**Comment by lxndrblz** [comment]
Please notice that your menu items in the `config.toml` should have a trailing slash. Such as:
```
[[menu.main]]
name = 'Uses'
url = '/uses/'
weight = 3
```

Check the ReadMe as a reference.

Would you mind trying the newest update in the branch on your staging server? Your site executed locally just fine.

**Comment by msfjarvis** [comment]
> Please notice that your menu items in the `config.toml` should have a trailing slash. Such as:
> 
> ```
> [[menu.main]]
> name = 'Uses'
> url = '/uses/'
> weight = 3
> ```
> 
> Check the ReadMe as a reference.
> 
> Would you mind trying the newest update in the branch on your staging server? Your site executed just fine locally.

That fixed it!

**Comment by msfjarvis** [comment]
```
WARN 2020/05/23 22:02:15 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
```

Does spew out this warning though

**Comment by lxndrblz** [comment]
Yeah, I am aware of this. Before commiting this to the master I'll change it to .Permalink. Just wanted to make sure we are on the right track.

**Comment by lxndrblz** [comment]
RefPermalink seemed to do the trick. 👍

**Comment by gusper** [comment]
@lxndrblz This helped me understand why the highlighting wasn't working on my site. I tried to add a note to the wiki and push back but I'm either failing that IQ test or just don't have access to do so. Adding a note here instead in case you think adding a note about the trailing slash to the wiki is worthwhile.

**Comment by lxndrblz** [comment]
@gusper Can you please send your note here? The wiki is not publicly writable.

**Comment by gusper** [comment]
Sure. Was just going to add something along the lines of:

> Please note the trailing slash (`/`) in the `url` property is required to enable properly highlighting the current page.

To this section of the [Essential Steps](https://github.com/lxndrblz/anatole/wiki/1%EF%B8%8F%E2%83%A3-Essential-Steps#setting-up-the-navigation-items) page.
