### ISSUE TITLE
RSS support

### ISSUE THREAD

**Issue by ericswpark** [lxndrblz/anatole#203]
Can anatole add RSS support for posts?

**Comment by lxndrblz** [comment]
@ericswpark  Thanks for bringing this up. RSS has been supported for quite a while:

https://github.com/lxndrblz/anatole/blob/3971e373205483aa7530cd2037dfaed644253628/layouts/partials/head.html#L60-L63

Did you have any issues using it?

**Comment by ericswpark** [comment]
Hi, I didn't know anatole already had support for RSS, sorry! I did check the README but didn't see anything about RSS so I assumed there was no support yet.

I noticed the RSS feed also includes pages for some reason, including hidden pages (pages not linked in the navbar). Is there a way to get the RSS feed to only show articles posted?

Also, can the RSS feed be added as an icon next to the social links, like the GPG key?

**Comment by lxndrblz** [comment]
Thanks for making me aware that the Readme currently does not mention the RSS feed. It certainly makes sense to add it there as well.

Regarding your first question: With the default settings this is not possible. However, you can always override the default rss.xml template. Check out the [following link](https://gideonwolfe.com/posts/sysadmin/hugo/hugorss/), it will describe on how that's done. Basically, you would include an additional check to make sure you are only showing linked pages.

Yes, you can add the RSS feed quite easily. You have to add another social icon like this:
```toml
[[socialIcons]]
icon = "fas fa-rss"
title = "rss"
url = "/index.xml"
```
It will give you a link this:
![image](https://user-images.githubusercontent.com/12200062/119390615-33e29a80-bcc5-11eb-8380-c2871de32300.png)

Hope that helps.

**Comment by ericswpark** [comment]
Hi @lxndrblz thanks for the reply. Just found an easier way of excluding pages from the RSS feed. It seems like the RSS feed is generated in subdirectories as well, so all I have to do to only have blog posts show up in the RSS feed is to use the URL:

    <website>.com/blog/index.xml

I'll submit a PR soon to add the information to the README.
