### ISSUE TITLE
Disqus not showing comments.

### ISSUE THREAD

**Issue by tldrafael** [lxndrblz/anatole#211]
First, thank you for this great hugo theme.

**Describe the bug**
I'm not being able to enable Disqus at all on my website. Followed #3 and #42 and tried many combinations of setting `type: post` or `type: posts`, and rechecked many times my disqus settings, everything seems fine.

**To Reproduce**
You can check more detail about my blog code [here](https://github.com/tldrafael/blog_professional) and the website [here](https://rtoledo.me).  It's built and deployed on Netflify.

**Expected behavior**
Expected to see the Disqus comments at the end of each post.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser Mozilla Firefox 89.0
 - Version of the Theme v1.0.0 
 - Version of Hugo Hugo 0.75.1
  
 ****
Would you have any clue of what could be happening?

**Comment by lxndrblz** [comment]
@tldrafael You were almost there. Simply move the `disqusShortname`  from below `[params]` to the section above, where the `baseURL` or `theme` are defined.

**Comment by tldrafael** [comment]
What a silly mistake haha. 

It worked @lxndrblz. Thanks a lot.
