### ISSUE TITLE
How can I add custom font icons (Academicons) to Anatole?

### ISSUE THREAD

**Issue by HerminioSabino** [lxndrblz/anatole#214]
I'm trying to add an icon from the academic package (https://jpswalsh.github.io/academicons/), but to no avail.

Even following the steps on the page and adding the css I did not get success
so my question
How can I add Academic icons to my hugo theme?
I know how to modify fa icons, but academic is ai icon.

I want to thank you for the excellent work..

Regards

Herminio Sabino

**Comment by lxndrblz** [comment]
@HerminioSabino  I am glad you like the theme. 

You can add these icons like any other custom CSS, with a minor catch. Firstly, see the description on custom CSS [here ](https://github.com/lxndrblz/anatole#custom-css) for any question.

The steps are as following:

1. Place the academicon.css in the `assets/css/` folder, you might have to manually create the css folde
2. Link the acadmeicon.css in the `config.toml` by setting the `customCss param to `customCss = ["css/academicons.css"]`
3. Additionally you will have to copy the `fonts` folder from the downloaded zip file to your `static` folder
4. Link the icons in your sidebar, like this:

```toml
[[socialIcons]]
icon = "ai ai-google-scholar-square ai-3x"
title = "Google Scholar"
url = "https://scholar.google.com/"
````
This will give you a nice Google Scholar logo that blends well with the other icons.

![image](https://user-images.githubusercontent.com/12200062/122634862-a7b36f80-d0d8-11eb-90fb-124724d021af.png)


Please close the issue, if you found this comment helpful.

**Comment by HerminioSabino** [comment]
I want to thank you for the quick response.

i am trying to reproduce the step by step but i am not having success.
I think the problem is in the allocation of .css files.

Is the assests folder I need to copy the files that already contains the style.css and markupHighlight.css files?

follow the attached images

![image](https://user-images.githubusercontent.com/27819904/122643896-c02b8600-d0e8-11eb-9d12-b3ed85652656.png)

![image](https://user-images.githubusercontent.com/27819904/122643908-c91c5780-d0e8-11eb-93aa-3fedc9600587.png)

![image](https://user-images.githubusercontent.com/27819904/122644101-d6861180-d0e9-11eb-9445-82a4c1d52c17.png)

Again I want to thank and remember that I'm a beginner in this universe and I'm using the theme from Rstudio.

Thanks

**Comment by lxndrblz** [comment]
@HerminioSabino Thanks for your feedback. A couple of notes:

I would create a new separate assets folder in the root directory of your Hugo site and place a subfolder called  css within the newly created folder.  I advise against placing it in the folder where thee `style.css` is located, as these are specific to your setup.

You don't need the .min.css version of the font as Hugo and Anatole will minify the custom CSS for you.

Also don't forget to copy fonts folder to the `static` folder, as the CSS relies on the fonts being served on your site.

If you are still having issues, it would be good if you could check in the web developer tools, if the css file is linked and if there are any errors, such as missing fonts.

Let me know if you still have any issues. I am here to help.

**Comment by HerminioSabino** [comment]
Hi, 
even though I performed all the suggested procedures and checked for any errors, I couldn't perform the procedure I want.

I'll try to build from scratch again to try to work around this problem.

thank you very much for your attention

**Comment by lxndrblz** [comment]
@HerminioSabino Are you getting any errors in your browser developer tools?

**Comment by HerminioSabino** [comment]
@lxndrblz  I'm not getting any error!

**Comment by KourosZanbouri** [comment]
@lxndrblz I am having the same issue. Can you elaborate clearly on how I can add Academicons to my theme?

I added Anatole as a submodule; I forked your git and changed the submodule to my fork ( to push my changes to theme locally )
what should I do now ?! Please be specific
