### ISSUE TITLE
Create a publications/project page

### ISSUE THREAD

**Issue by lxndrblz** [lxndrblz/anatole#221]
I am looking for a way to present my projects and publications in a clean and visually appealing way that is different form the blog.

**Comment by strangeglyph** [comment]
Love to see that you are working on this, I am very excited to see the result! 

For me, the main feature that is missing is being able to declare co-authors, publication venue (+ link to publication) and maybe a direct download link, ideally from a posts front matter. Bonus points if it supports Academicons out of the box.
