### ISSUE TITLE
viewport larger than 1920px wide causes content overlaps with high content ratio

### ISSUE THREAD

**Issue by ghost** [lxndrblz/anatole#231]
**Describe the bug**
sidebar content overlaps main window when using a viewport larger than 1920px wide

**To Reproduce**

1. Set contentratio in params.toml to 0.8 or greater (or change in browser dev tools)
2. View website in a window more than 1920px wide

**Expected behavior**
Content automatically scales and doesn't overlap

**Screenshots**
content ratio set to 0.8 and width of 1920px: https://snipboard.io/Xl8haF.jpg
content ratio set to 0.8 and width of greater than 1920px: https://snipboard.io/5g9nor.jpg

**Desktop (please complete the following information):**

- Browser: Chrome and Edge, both latest versions
- Version of the Theme: Latest
- Version of Hugo: v0.85.0

**Additional context**
To check it wasn't an issue with any changes I made in my CSS, I manually edited the content ratio via the browser on your website and observed the same issue.
I would rather have a smaller sidebar but setting it smaller than 30% causes unintended content overlap issues.

**Comment by lxndrblz** [comment]
@lxndrblz Thanks for filing this bug. I can confirm that this issue occurs if a content ratio is chosen greater than 0.7. The problem appears to be the calculation of the sidebar width and the fixed padding left.

The way the content presentation should be optimised for large screens is by adding a padding of 20% to either site of the screen. It appears if that is not happening correctly. I'll have to investigate that and see how it could be resolved.

**Comment by jhlasnik** [comment]
Any update on when this might be fixed?  I'm hitting the same issue.

**Comment by lxndrblz** [comment]
@jhlasnik Thanks for asking! 

Unfortunately, I don't have any solution for this bug just yet. However, this issue is still on top of my to-do list, and I am expecting to find a solution within the next days.
