### ISSUE TITLE
Having a "Series" of posts

### ISSUE THREAD

**Issue by SchabrechtsK** [lxndrblz/anatole#234]
**Is your feature request related to a problem? Please describe.**
I would like to add series to my blog posts. So I would like to group posts that have been broken up in Part I, II, III, ...

**Describe the solution you'd like**
I would like to set `series` in the front matter so when looking at the post you see a `See also` or `Related` or something like this.

**Describe alternatives you've considered**
I thought about working with the tags or with the category. But that would not do it justice.

**Additional context**
Well, I added the taxonomies in the config.toml:
```
[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
```

And the series in the Front Matter:
`series: 'Retrospective'`

But then I get the following error:
```
render of "page" failed: execute of template failed: template: _default/single.html:7:6: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:36:44: executing "_internal/opengraph.html" at <.>: range can't iterate over Retrospective
failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:7:6: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:36:44: executing "_internal/opengraph.html" at <.>: range can't iterate over Retrospective
```

Or maybe I'm missing something? 

PS: Great work on this theme!

**Comment by lxndrblz** [comment]
@SchabrechtsK Did you try setting the series to a list in the front matter?

```yaml
series:
- Retrospective
```

**Comment by SchabrechtsK** [comment]
@lxndrblz That indeed fixes the error.
This also makes the `/series/<series_name>` url available.

But each blog post in that series is not linking to another?
Is that part a missing feature or am I missing something?

**Comment by lxndrblz** [comment]
@SchabrechtsK That is indeed still a [todo](https://github.com/lxndrblz/anatole/projects/1). 
Personally, I think this feature should be fairly easy to fix as there are numerous examples online.

Unfortunately, currently I am quite busy with my other projects and can not dedicate much time. However, if you are wanting to develop this feature and have it added to the theme then please send me a PR and I'll review it.
