### ISSUE TITLE
Removing author name from page title.

### ISSUE THREAD

**Issue by sirwhinesalot** [lxndrblz/anatole#235]
Is there a way to remove the author name from the page title? 
I'm referring to this little bit:

```html
<title> {{ .Site.Params.author }}{{ with .Title }} | {{ . }}{{ end }}</title>
```

I could just clone the theme and change this in the clone, but this seems to be something that should be a configuration option on the theme. It doesn't make sense to constantly show the author name on a single author blog.
Did I miss something?

**Comment by lxndrblz** [comment]
@sirwhinesalot Currently there is no configurable way to change this.

As you already noted, one way would be to clone the theme and adjust that bit, as necessary.
A smarter way, would be to add the module as a submodule and in your "local" layouts folder create a partials folder and place a modified copy of the `head.html` in there. This will then have precedence over the one of the theme. 

Personally, I don't see a need to make this optional, as it gives consistency across all the sites and as this theme is meant for personal websites I believe it is fine to display the authors name.
