### ISSUE TITLE
The /posts endpoint shows a list (grouped per year) of posts. Having this as the home.

### ISSUE THREAD

**Issue by franferri** [lxndrblz/anatole#237]
Will be possible (maybe it is, I'm new to Hugo) to have the /posts endpoint (the one that shows a list (grouped per year) of posts, just the titles, having  it this as the home?

**Comment by lxndrblz** [comment]
@franferri  I am sorry, but that is not possible by default. By default, this theme uses the `index.html` for the frontpage and the `list.html` for the archive page. If you want the compact view on the frontpage too, you would have to modify the `index.html`. You could do this either by cloning the theme or overriding the specific file locally.

Hope that helps.
