### ISSUE TITLE
Website url in the repository details is incorrect

### ISSUE THREAD

**Issue by vidhi-mody** [lxndrblz/anatole#239]
**Describe the bug**
The current url in the repository details is [themes.gohugo.io/theme/anatole/](https://themes.gohugo.io/theme/anatole/) which redirects to a 404 page.

**Expected behavior**

The url in the repository details should be changed to [themes.gohugo.io/themes/anatole/](https://themes.gohugo.io/themes/anatole/)

**Screenshots**
<img width="350" alt="Screenshot 2021-08-09 at 11 10 31 PM" src="https://user-images.githubusercontent.com/49282105/128749684-46e7150d-d355-43a1-a5ff-c8d528abb89c.png">
<img width="1440" alt="Screenshot 2021-08-09 at 11 10 17 PM" src="https://user-images.githubusercontent.com/49282105/128749732-337e5e02-02a6-4793-9fef-3a8c2e477115.png">

**Comment by lxndrblz** [comment]
@vidhi-mody Thanks for flagging this up. It should be resolved now.
