### ISSUE TITLE
contact set-up

### ISSUE THREAD

**Issue by PursuitOfDataScience** [lxndrblz/anatole#240]
Hi,

I used Anatole theme to build my website, and it looks great. One thing I haven't figured out is how I set up contact section. When I tentatively tried to input email and related info and then sent it, it showed me 404 as the picture attached shown. Could you please shed some light in this regard? Thanks!

![image](https://user-images.githubusercontent.com/54338793/129375864-98520714-cdb7-40fc-b091-8be07aa87fd0.png)

**Comment by lxndrblz** [comment]
@PursuitOfDataScience It looks, as if you haven't configured a Formspree URL in your `param.toml`. Make sure to properly set `contactFormAction` to your own Formspree URL.

This is required, as the form will post the information to that domain, where it will be further processed. The theme can't notify you of a comment without the Formspree integration.

Hope that clears things up.

**Comment by PursuitOfDataScience** [comment]
Thanks for your response. Followed by your input, I created a Formspree URL, but it is still nebulous for me to know where the next steps are. Where is `contactFromAction` you mentioned? How can I input the URL to `params.toml`?

**Comment by lxndrblz** [comment]
https://github.com/PursuitOfDataScience/personal-website/blob/master/config/_default/params.toml

In there, comment out the `contactFromAction` and add your own URL.

**Comment by PursuitOfDataScience** [comment]
It worked! Thanks! I also have two minor questions. The first one is the top tab section fonts are kind of small. It would be nicer if it is bold and font size is a bit bigger. Where can I set it up? Also, the line that splits the two column is sort of in the middle. I'd like to shrink the area of the left side and leave more space for the right side. Is there a way to do it? Appreciate your help!

![image](https://user-images.githubusercontent.com/54338793/129383205-54e42336-a16a-4a9b-ab27-fe91eb196c8c.png)

![image](https://user-images.githubusercontent.com/54338793/129383512-332ac7cc-dd55-43fc-8c96-05460efc7e5b.png)

**Comment by lxndrblz** [comment]
@PursuitOfDataScience  You can adjust the size of the navbar by creating a custom CSS. Let me know if you have any troubles doing so.

The content ratio of the sidebar to the content can be adjusted by modifying the `contentratio` variable, as explained here:
https://github.com/lxndrblz/anatole#changing-the-sidebarcontent-ratio

**Comment by PursuitOfDataScience** [comment]
Thanks!
