### ISSUE TITLE
Questions regarding Rmarkdown and Font Faces

### ISSUE THREAD

**Issue by PursuitOfDataScience** [lxndrblz/anatole#241]
Hi,

After playing around the theme for a while, I have few follow-up questions after your help yesterday. 
1. Since all of my blog posts are generated by using Rmarkdown rather than markdown, how should I input tags and descriptions for each post?
2. All the blog titles are all caps, which would make viewers hard to read. Is it possible to switch them back to normal titles without all caps?
3. Regarding the tab fonts I asked yesterday, could you help me write a CSS so that I can customize the font and face by myself?

Thanks for your help!

**Comment by lxndrblz** [comment]
Hi @PursuitOfDataScience 

Unfortunately, I am not too familiar with Rmarkdown, but you should still be able to add the tags and description manually to the frontmatter of your posts (similarly as you would do for a post written in normal markdown).

Yes, that could be changed, again using a custom CSS. You would need to create a custom css file and add the following code:

```css
.post .post-title h1 {
    text-transform: none;
}
.post .post-title h3 {
    text-transform: none;
}
``` 
You can make the text of the navigation larger and bold as following:
```css
header .nav__list {
    font-size: 1.9rem;
    font-weight: bold;
}
```

You'd simply need to add both code blocks to your custom css file and reference it in your config file.

**Comment by PursuitOfDataScience** [comment]
Thank you so much for your instruction! I added a css folder inside of static folder and put the `.css` file with the code written by you. When I referenced it by `customCss = ["css/custom.css"]` in `parms.toml` file, it gave me an error and the website didn't get rendered. Could you please take a look for me?

**Comment by lxndrblz** [comment]
@PursuitOfDataScience  Would you mind sharing the error that you got?

**Comment by lxndrblz** [comment]
Ah, found the error: The CSS folder goes in the `assets` folder not the `static` folder.

**Comment by PursuitOfDataScience** [comment]
Thanks! It worked!

Here is the follow-up question I have. As you can see, the blog text is sort of greyish, which does not have a stark contrast to the R code snippet. I guess the question is on the same line, which is how to make the text a tad larger and black rather than pale?

![image](https://user-images.githubusercontent.com/54338793/129575342-9299e569-90a8-44e2-8eba-ec15445c6c6c.png)

Regarding to the tags and descriptions of R markdown files, I had done a lot of homework prior to the questions. Unfortunately, R markdown file has rigid structure in the beginning, as shown below. I was trying to find a way to embed descriptions, but once I changed the heading, the entire file would be corrupted. Maybe you can shed some light in this regard?

![image](https://user-images.githubusercontent.com/54338793/129576255-dc6423ee-2a0d-4b6e-bcd1-200200aff2db.png)

**Comment by PursuitOfDataScience** [comment]
I changed the text color successfully, but the text size remains small. 
I thought this snippet would change the text size, but it doesn't. 
`.post .post-content h4 {
  /* color: var(--heading-color); */
  font-size: 3.0rem;
}`

**Comment by lxndrblz** [comment]
@PursuitOfDataScience Sorry, I forgot responding.

There are two different ways for syntax highlighting. You can either use the one you are currently using or use the Chroma code highlighting. For the latter, please see the instructions [here](https://github.com/lxndrblz/anatole#syntax-highlighting).

For the former, you would need to adjust the css for the `code` element.

```css
code {
    color: red;
    font-size: 2em;
}
```

The colour of the content is controlled by the variable `--body-color` in the CSS file. Simply change the values in-place or reassign the variable.

**Comment by PursuitOfDataScience** [comment]
Thanks for your helpful input. When I input the following code, it only increases the font of the title, yet the actual content text in each blog does not change at all in terms of its size. I am wondering if there is any other parameters that control the actual text rather than title? 
```
body {
  font-size: 2.5rem;
}
```

**Comment by lxndrblz** [comment]
Yes, you would need to adjust the font-size of `p`. See this line:
https://github.com/lxndrblz/anatole/blob/e1bfb62880c7a5da85b3b24fe0f02078f17b90ba/assets/css/style.css#L62-L66

If you want all fonts to appear slightly bigger, then you would need to adjust only the `font-size`, as rem's are relative to the default font-size:

https://github.com/lxndrblz/anatole/blob/e1bfb62880c7a5da85b3b24fe0f02078f17b90ba/assets/css/style.css#L47-L51

Hope that helps.

**Comment by PursuitOfDataScience** [comment]
Thanks for your help. All my questions are solved!

**Comment by Kavinraja-G** [comment]
@PursuitOfDataScience @lxndrblz  I'm trying to use custom font with `customCss` it didn't work for me. It always renders with the default font. Anything I'm missing here?

Code: https://github.com/Kavinraja-G/Kavinraja-G.github.io/tree/feat/custom-font
