### ISSUE TITLE
Mark a post as outdated automatically after a period.

### ISSUE THREAD

**Issue by SchabrechtsK** [lxndrblz/anatole#250]
**Is your feature request related to a problem? Please describe.**
Not to a theme-related problem but related to a problem in my field of expertise. I use this theme for a development-related blog. Now, as you might know, in our dev world things can go stale really fast if we're talking about actual code posts. Frameworks change, best practices change, and so forth.
This means any post older than x months might be outdated and not be correct anymore.

**Describe the solution you'd like**
So I would like to add an option in the Front Matter which you can toggle to mark the content as a type that can go stale. If this option is active then an older post, starting from a year f.e., would have a small note at the top that the content might be scale.

**Describe alternatives you've considered**
Well, you could delete the content but then you have broken links and it does not showcase your expertise anymore.
You could also manually add the note.
Both, however, require manual labor which we would like to avoid.

**Additional context**
Another dev I know added it to their site: https://brunty.me/post/display-message-on-old-hugo-entries/
If you want I'm more than willing to add this myself, but I wanted to check in first what your thoughts are on this subject 😄

**Comment by lxndrblz** [comment]
@SchabrechtsK I can definitely see a need for such as a feature. Would you mind sending a PR once you are done?
