### ISSUE TITLE
Images in frontmatter make the build fail

### ISSUE THREAD

**Issue by rhjensen79** [lxndrblz/anatole#252]
**Describe the bug**
When adding 
images: "images/andrew-neel-1-29wyvvLJA-unsplash.jpg"
to frontmatter, the build fails with the following error :

ERROR 2021/09/10 10:17:04 Failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:7:6: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: partials/head.html:198:5: executing "partials/head.html" at <partial "schema.html" .>: error calling partial: "/Users/jensenr/Downloads/robert-jensen.dk/themes/anatole/layouts/partials/schema.html:76:33": execute of template failed: template: partials/schema.html:76:33: executing "partials/schema.html" at <.Params.images>: range can't iterate over images/andrew-neel-1-29wyvvLJA-unsplash.jpg
Total in 5 ms

**To Reproduce**

1. Create new empty site
2. install latest Anatole theme
3. Create a new post
4. Add images: "url to image" to you frontmatter
5. See the build fails

**Expected behavior**
A new build.
It worked in earlier versions on Anatole theme

**Desktop (please complete the following information):**

- OS: OSX
- Version of the Theme : Latest
- Version of Hugo : hugo v0.87.0+extended darwin/amd64 BuildDate=unknown

**Additional context**
It's been working without any problems, but when i tried to upgrade the theme my build fails. 
Creating a new theme, with the steps described above, generates the same error.

**Comment by lxndrblz** [comment]
@rhjensen79 Can you please confirm in which folder you'd copied the image?

**Comment by rhjensen79** [comment]
Yes. So one example of my working blog today, has the following value 

images: "images/ian-taylor-jOqJbvo1P9g-unsplash.jpg"

And the picture refered is in /static/images/

Note my folder structure, is /content/posts/blogname/index.md
And under each blogname, i also have a folder called images, where i put the images from the current post. 

Hope that clarified it (i understand if it did the oppesite :-) )

btw. Thanks :-)

**Comment by lxndrblz** [comment]
Thanks for clarifying. I am currently away fromy computer. I'll try to reproduce it as soon as I get back.

**Comment by rhjensen79** [comment]
Nu rush, and thanks. Just wanted to register it, now that i was able to reproduce it. 
The workaround is pretty simple. Just # all images frontmatter lines :-)

**Comment by lxndrblz** [comment]
@rhjensen79 Please apologize the wait. I was able to reproduce the error this morning. To fix this issue you have to define the image as a list, rather than assigning it directly to the variable. This is because in some scenarios multiple images may be used, such as Twitter cards where you can select the appropriate image to preview. The issue you encountered links the image to the schema.org metadata, which gets picked up by the search engine.

How to fix it:
Instead of:
```
images: "images/andrew-neel-1-29wyvvLJA-unsplash.jpg"
```

Try:
```
images:
- "images/andrew-neel-1-29wyvvLJA-unsplash.jpg"
```

I hope that helps.

**Comment by rhjensen79** [comment]
Thanks @lxndrblz 

I just changed all my images to lists, and it worked perfectly. 
Also i was not aware, of the possibility, of having multiple images, so you just enhanced my blog, quite a bit. 
Thanks a lot for your help (and your work on this theme) :-)
