### ISSUE TITLE
Subsection Headings on Home page

### ISSUE THREAD

**Issue by strangeglyph** [lxndrblz/anatole#253]
**Is your feature request related to a problem? Please describe.**
I currently have a brief "About Me" section on my home page, followed by the auto-aggregated recent posts summary. However, I find the visual separation between the two sections not as distinct as I'd like it.

**Describe the solution you'd like**
I'd like to be able to configure subsection headings for the aggregated content and ideally also configure the vertical separation to the content included from `_index.md`.

**Describe alternatives you've considered**
I have tried to end the `_index.md` with a subsection heading, but this heading ends up visually closer to the bio content then the aggregated content, so the result looks off.

I also noticed that the theme's `layouts/index.html` contains a div for `params.mainSectionsTitle`, but adding that setting to the `config.toml` does not appear to have any obvious effects. As far as I can tell, the div is not even included in the rendered HTML.

**Comment by lxndrblz** [comment]
@strangeglyph Please apologize my late reply. Somehow I must have missed your issue.

Thanks for your in-depth explanation which greatly helped me.

You have to set the `mainSectionsTitle` in the frontmatter of your `_index.md`; for example like this:
````md
author = "Hugo Authors"
mainSectionsTitle = "Foo"
````

This will give you something like this (mind the headline named foo):
![image](https://user-images.githubusercontent.com/12200062/134683189-40d99627-a85f-4fbe-829f-1045e78dcb88.png)

Does this answer your question?

**Comment by strangeglyph** [comment]
Thank you, yes, that's exactly what I was looking for.
