### ISSUE TITLE
Error: executing "partials/head.html" at <resources>: wrong type for value; expected resources.ResourceTransformer; got resource.Resource

### ISSUE THREAD

**Issue by AcademicusChamaeleon** [lxndrblz/anatole#267]
Dear Alexander,

I use anatole theme with R blogdown, But I encounter some issues when I included custom CSS. The error message when I launched the website is the following.

Launching the server via the command:
  C:/Users/barry/AppData/Roaming/Hugo/0.89.4/hugo.exe server --bind 127.0.0.1 -p 4321 --themesDir themes -t anatole -D -F --navigateToChanged
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:7:6: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "\personal_website\themes\anatole\layouts\partials\head.html:75:31": execute of template failed: template: partials/head.html:75:31: executing "partials/head.html" at <resources>: wrong type for value; expected resources.ResourceTransformer; got resource.Resource

I would really appreciate your help

**Comment by lxndrblz** [comment]
@AcademicusChamaeleon Thanks for reaching out - Just to confirm, would you mind sharing where you'd put your custom CSS file and the line you had added to your config?
