### ISSUE TITLE
Change images in dark mode

### ISSUE THREAD

**Issue by Hermit12** [lxndrblz/anatole#268]
**Is your feature request related to a problem? Please describe.**
I'd like to switch some pictures to their inverted form for better readability in dark mode.

**Describe the solution you'd like**
I tried this solution found [here](https://github.com/wowchemy/wowchemy-hugo-themes/discussions/1961#discussioncomment-696357) but I cant get it to work with this theme. Can you help me implementing it?

Pictures I'd like to invert are .png files.

Many thanks for this awesome theme!

**Comment by lxndrblz** [comment]
@Hermit12 Thanks for your feature request.

I did a little bit of digging and looked at the source you had linked. 

A sensible approach would be to extend the current figure shortcode with a parameter for the mode.


One thing I have noticed though is that you would need to upload two versions of the same image (a dark one and a light one). Are you aware of that?

**Comment by Hermit12** [comment]
Sorry for my late reply and thanks for your answer. I am aware of the fact that I need two kinds of images, the original and the invers one. An automatic conversion wouldn't always bring the right results and also not every image should be converted.
A workaround with shortcode would be nice. The approach in the source I linked should also work, but I couldn't find the name of the "dark" class.  If you change the `.dark` to the specific class in this theme it should work, if you copy 

```
body:not(.dark) .mongo_dark {
  display: none;
}
.dark .mongo_light {
  display: none;
}
```

into the CSS file, or am I wrong?

**Comment by lxndrblz** [comment]
After careful consideration I have decided to mark this request as "wont fix" as the overhead caused does not allign with the initial idea of a small and minmalistic theme.
