### ISSUE TITLE
How could I move the thumbnail to the left? 

### ISSUE THREAD

**Issue by denis-or** [lxndrblz/anatole#269]
I don't know about update the picture of the thumbnail in css files. How could I move the thumbnail to the left, por example?

**Comment by lxndrblz** [comment]
@denis-or Thanks for reaching out to me. Would you mind clarifying which thumbnail you are talking about? Preferably, include a screenshot. 👍

**Comment by denis-or** [comment]
> @denis-or Thanks for reaching out to me. Would you mind clarifying which thumbnail you are talking about? Preferably, include a screenshot. +1

Hi Alexander. Sorry about that. So, I couldn't change the place of post thumbnails. This thumbnail is enabled in rmd, inside the post parameters:

`thumbnail: "images/new_image.png"`

Its necessary the picture be in `static/images`, right? Ok. let's to the "problem":

The picture is shown in top of the post list:

![image](https://user-images.githubusercontent.com/49842454/145613744-048cc78a-065f-4ab0-aa9e-2227df3e452d.png)

I really want to put this image on the right side. Something like as:

![image](https://user-images.githubusercontent.com/49842454/145614032-9b2353b8-de65-497f-9318-b9388d655a73.png)

Did I explain correctly?

**Comment by lxndrblz** [comment]
@denis-or Thanks for the clarification. This helps a lot. I'll have a look at it.

**Comment by lxndrblz** [comment]
@denis-or Hi there, I spend the holidays fiddling around your problem. Unfortunately, there is no easy solution to your problem, as the theme was never intended for this. The best that I could achieve was this:

![image](https://user-images.githubusercontent.com/12200062/147391916-52856257-d070-498c-9bf2-172538495ff1.png)

What I did is that I've wrapped the items on the left side in additional div and then used a CSS flexbox to distribute the textual information and imagery within the post div.  You could obviously vary the distribution of the two columns according to your liking and make the image a bit smaller. To get to this point, you would need to extensively modify the index.html and make extensive changes to the CSS, which makes updates to future versions more troublesome. Personally, I don't see much benefit in this change. Nevertheless, I hope my advice was useful for you.

Regarding your other question: Yes, the image needs to go into the static folder.
