### ISSUE TITLE
Problem building example site

### ISSUE THREAD

**Issue by ThisIsJeron** [lxndrblz/anatole#271]
**Describe the bug**
When trying to preview the exampleSite, I followed the exact instructions and I received this error:

`Start building sites … 
hugo v0.84.0+extended darwin/amd64 BuildDate=unknown
Built in 53 ms
Error: Error building site: "/Users/jeron/projects/personalSite/anatole/exampleSite/content/english/post/rich-content.md:26:1": failed to render shortcode "tweet": failed to process shortcode: template: _internal/shortcodes/tweet.html:6:82: executing "_internal/shortcodes/tweet.html" at <index .Params 0>: error calling index: value has type int; should be string`

**To Reproduce**

Following Preview the exampleSite steps

**Desktop (please complete the following information):**

- OS: macOS
- Version of Hugo (run a `hugo version` if unsure): hugo v0.84.0+extended darwin/amd64 BuildDate=unknown

**Comment by lxndrblz** [comment]
@ThisIsJeron I think you are getting the error due to an outdated hugo version. Would you mind trying to update to 0.89 and see if the issue persists?
