### ISSUE TITLE
How to change the font size of Katex math symbol and backtick text?

### ISSUE THREAD

**Issue by xiangli2pro** [lxndrblz/anatole#277]
Hello there, thank you for the beautiful template. I want to ask if it's possible to change/reduce the font size of the Katex math symbols and backtick text (e.g. `text`)? It seems like on the website (see the screenshots), the math symbols and backtick texts are always larger than the regular text, it would be much better if their sizes can be reduced. 

I have searched online and didn't get much useful information. There is a [post](https://bwaycer.github.io/hugo_tutorial.hugo/tutorials/mathjax/) talking about changing the size of MathJax symbols, but didn't find anything about Katex symbols. And here is a [post](https://www.yulingyao.com/blog/2021/BF/) in which the math symbol looks in normal size, so I think it's possible to do so but have no idea how to do it. Do you have any suggestions? Any information is greatly appreciated.

screenshot1 (the Katex math symbol is larger)
<img width="604" alt="Screen Shot 2021-12-23 at 1 23 33 AM" src="https://user-images.githubusercontent.com/78754416/147197670-58dc89fa-6645-4eb6-b7db-4624cb93db86.png">

screenshot2 (the backtick text is larger)
<img width="612" alt="Screen Shot 2021-12-23 at 1 24 11 AM" src="https://user-images.githubusercontent.com/78754416/147197685-d1e3abba-90c5-40e7-aca0-69e99399d0dd.png">

**Comment by lxndrblz** [comment]
@xiangli2pro Hi there, the CSS identifiers you are looking for are code and Katex. You can override them as following in your custom CSS.
```css
code {
}
.katex {
}
```
You would need to adjust the font-size of these according to your liking. However, note that the Katex uses a different font than the theme, therefore, the characters might still look slightly different.

Hope this helps. Going to close this issue. Feel free to reopen it if you need additional information.
