### ISSUE TITLE
Move "outdated content" above TOC

### ISSUE THREAD

**Issue by gummigroda** [lxndrblz/anatole#285]
**Is your feature request related to a problem? Please describe.**
No, but a suggestion to make the design a bit clearer when TOC is enabled.

**Describe the solution you'd like**
Move the "outdated content" reminder above the TOC

**Current design**
![image](https://user-images.githubusercontent.com/15022172/147713264-ab890e9d-ad86-4400-bcd5-eecfbd5c9f22.png)

**Suggested design**
![image](https://user-images.githubusercontent.com/15022172/147713268-ef04b56f-68e1-4e71-8162-b33ec44e2fd9.png)

**Comment by lxndrblz** [comment]
@gummigroda Thanks for your recommendation. I agree that the disclaimer should come before any other content.
