### ISSUE TITLE
Separate the content of two menu items

### ISSUE THREAD

**Issue by Andrew-Schneider** [lxndrblz/anatole#288]
I want to have two different posts menu items listing different content in each. However when i create two items for this, all the posts in content subfolders is shown in both:
<img width="720" alt="Screen Shot 2022-01-05 at 11 52 40 AM" src="https://user-images.githubusercontent.com/47110721/148256831-2e3facb4-d3e4-4077-b383-c18298fbf65e.png">
<img width="720" alt="Screen Shot 2022-01-05 at 11 52 45 AM" src="https://user-images.githubusercontent.com/47110721/148256848-495352f6-59e1-4f82-877e-e6d0713acd85.png">

The result i want is shown in these two screenshots:
<img width="720" alt="Screen Shot 2022-01-05 at 11 45 46 AM" src="https://user-images.githubusercontent.com/47110721/148256999-a3eb2ff2-028d-4bb8-af96-86cdda194602.png">
<img width="720" alt="Screen Shot 2022-01-05 at 11 47 41 AM" src="https://user-images.githubusercontent.com/47110721/148257002-4ef7a633-8df4-4d02-809b-5172e4a2dabf.png">
this was done by changing some posts to drafts, taking a picture, then undoing that and changing a different post to a draft, not an actual solution.

From what i read in the Hugo docs having the separate folders with _index.md's in them should produce the functionality i'm looking for, but that doesnt seem to be the case. Any idea where i'm going wrong with this?

My site is: https://www.andrew-schneider.com/posts/
My code is at: https://github.com/Andrew-Schneider/andrew-schneider.com

**Comment by lxndrblz** [comment]
@Andrew-Schneider Thanks for your great explanation and providing access to the repository.

You could distinguish between those different subjects by linking them to the relevant categories. 

Categories can be accessed via /categories/<category name> i.e. /categories/math/. If this page is called, only the posts from this category are shown. For this to work, you might need to update the `list.html` to the latest version included in the theme.

![image](https://user-images.githubusercontent.com/12200062/148376610-d7227a55-538d-49c9-9c73-391b9cd305ff.png)

You could then link this endpoint to your menu items. In your case, the categories would be demo and math.

**Bonus Tip:**

For projects, you might also want to consider using the new projects feature that lets you easily define a range of projects through a data file. An example can be found on our data site.

https://anatole-demo.netlify.app/portfolio/

Hope that helps.

**Comment by Andrew-Schneider** [comment]
You were correct about updating to the newest anatole list.html. I was using a customized one that i hadn't realized was customized. 
However, now the posts are sorted by date (which i know is intended functionality) and i'm curious how to get similar functionality to the [custom one](https://github.com/arjungandhi/arjungandhi.com/blob/master/layouts/_default/list.html), though that's just something i think i'll need to do more research and learning to figure out.

Thanks for the help.
