### ISSUE TITLE
Help wanted: Use Single Dollar Symbol as inline formula delimiter

### ISSUE THREAD

**Issue by stark-zhang** [lxndrblz/anatole#306]
Hey there, I am try switch my personal blog form `hexo` to `hugo` because there are some bugs in the support of LaTeX rendering.

I just want to use `$...$` as the delimiter of inline math formula rather than `\\(...\\)`, because I am accustomed with the former one. How to configure that?

For example:

```markdown
There is an inline formula: $\int x \mathrm dx = \frac 1 2 x^2 + C$.
``` 

After rendered:
![image](https://user-images.githubusercontent.com/17326718/154003839-5b11a03c-6e4e-4ceb-b56b-4c082519e1a9.png)

**Comment by lxndrblz** [comment]
@stark-zhang Hi there, that's unfortunately nothing that could be configured or easily changed thorough the theme. 

If you want to configure Katex or Mathjax to use single dollar signs, you would need to configure the delimiters through some custom JavaScript code.

https://stackoverflow.com/questions/27375252/how-can-i-render-all-inline-formulas-in-with-katex

Please note that a single dollar sign might be error prone, as these can occur frequently within the normal flow of text.

**Comment by lxndrblz** [comment]
> so could you give some examples about errors caused by `$`? I need some case to test.

Unfortunately, I don't have a proper example. It might be worth playing around.

> Is there anyway to support these features of markdown? I had used them a lot in my blogs when I was using hexo, I have no idea to migrate them to hugo with anatole.

Hugo also supports subscript, highlight and strikethrough text. The syntax, however, is a bit different. Unfortunately, I am not sure if another markdown engine like Goldmark supports your hexo syntax.

I am sorry, I couldn't really help in this regard. Maybe it would be best to ask this Hugo specific questions over on the Hugo forum, as they are more related to hugo and its inner workings rather than the specifics of the Anatole theme.

**Comment by stark-zhang** [comment]
Thanks for your reply. I found the error of rendering of subscript and highlight occurs in you example site, too. And I think them should be fixed.
 
![image](https://user-images.githubusercontent.com/17326718/154453373-0bfac7fc-246d-4e7d-be2c-cd51d17b62cd.png)

**Comment by lxndrblz** [comment]
I can't reproduce your view. If you check the demo site all the Markdown in rendered correctly.

https://anatole-demo.netlify.app/post/markdown-syntax/

**Comment by stark-zhang** [comment]
thank you, it was caused by hugo configuration loading mechanism, it doesn't load configuration from `themes/anatole/exampleSite/config/*.toml` automatically. and it is solved by enabling unsafe mode for goldmark parser.

Now I meet new problem, complicated formula cannot be rendered with default `config.toml`. Here is my configs, with katex.
*I tried to update katex to `0.15.2`, but the complicated formula cannot be rendered neither.*

```html
    {{- $url := "https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css" -}}
    {{- $hash := "sha256-94CNZ/bJtwrBYZrXhCOBvpB4rZUzBnvAsirFv31TMGo=" -}}
    <link rel="stylesheet" href="{{- $url -}}" integrity="{{- $hash -}}" crossorigin="anonymous" />

    {{- $url := "https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.js" -}}
    {{- $hash := "sha256-bgI9WhLOPSUlPrdgHUg3rPIB2vq+D+mYkUTM3q0U8fw=" -}}
    <script defer src="{{- $url -}}" integrity="{{- $hash -}}" crossorigin="anonymous"></script>

    {{- $url := "https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/contrib/auto-render.min.js" -}}
    {{- $hash := "sha256-y39Mpg7V3D4lhBX4x6O0bUqTV4pSrfgwEfGKfxkOdgI=" -}}
    <script
      defer
      src="{{- $url -}}"
      integrity="{{- $hash -}}"
      crossorigin="anonymous"
      onload="renderMathInElement(
        document.body,
        {
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '\\[', right: '\\]', display: true},
            {left: '$', right: '$', display: false},
            {left: '\\(', right: '\\)', display: false}
          ],
          strict: false,
          output: 'html'
        }
      );"
    ></script>
```

you can find that `\\`, the line break symbol,  does not work:

```markdown
$$
f(x) = \begin{cases}
x^2 + 1 &\text{if } x \ge 0 \\
\ln |x| &\text{otherwise}
\end{cases}
$$
```
![image](https://user-images.githubusercontent.com/17326718/154609984-281c918b-3f9a-4e95-bccc-03ad9e8dc05c.png)

and the tag `equation` is not effective:

```markdown
$$
        \begin{equation}
        \begin{split}   a &=b+c\\
            &=e+f
        \end{split}
        \end{equation}
$$
```

![image](https://user-images.githubusercontent.com/17326718/154610182-3f4b6c5b-04ad-4057-ab8e-92317784869b.png)

And you can verify these formulas here: [KaTeX online demo](https://katex.org/#demo).

Could you give some suggestion about it?

**Comment by lxndrblz** [comment]
@stark-zhang You need to use three backslash as you need to escape the backslash:

```md
$$
f(x) = \begin{cases}
x^2 + 1 &\text{if } x \ge 0 \\\
\ln |x| &\text{otherwise} \\\
\end{cases}
$$
```

![image](https://user-images.githubusercontent.com/12200062/154808648-aed363ad-00ee-4d85-822b-48eb3950471a.png)

**Comment by stark-zhang** [comment]
Thank you, it works.

the KaTeX seems to start working before HTML generation, the escape is done after this, so KaTeX cannot work well without some hacking method. I think it's an extra load for me, a new fish of HTML/CSS/JS. and I decide to stop switching to hugo because the maintainers of hugo is negative to support LaTeX rendering.

Thanks for all of your helps again!
