### ISSUE TITLE
Social icon not show

### ISSUE THREAD

**Issue by Sptandi** [lxndrblz/anatole#31]
![image](https://user-images.githubusercontent.com/4879509/83330452-29134680-a2b9-11ea-9ac6-b78f9763f451.PNG)

I already turned off adblock, but still not working.

**Comment by lxndrblz** [comment]
Would you mind providing me two pieces of information?

Is there a way I can access your site to try it myself? If yes, please provide the URL.

Could you please also post the content of your config.toml?

**Comment by Sptandi** [comment]
Sorry but currently it's still in localhost



**config.toml**
```
baseURL = "https://example.org/"
languageCode = "en-us"
title = "Saputro Andi"
theme = "anatole"
paginate = 10
canonifyurls = true

[params]
    title = "Saputro Andi"
    author = "Saputro Andi"
    description = "Passionate developer"
    
[[params.social]]
    name = "Github"
    icon = "fab fa-linkedin fa-2x"
    weight = 1
    url = "https://github.com/sptandi/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/sptandip/"

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2
```

**Comment by lxndrblz** [comment]
Thanks for sharing the configuration!  Can you try to set the icon to just the corresponding fontawesome class?

 In case of GitHub that would be the following:

`[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"`

You might want to check the config.toml in the exampleSite folder.

**Comment by Sptandi** [comment]
Wow thanks, it's work

I didn't notice that the setting in the params
