### ISSUE TITLE
Separate profile picture for light/dark theme

### ISSUE THREAD

**Issue by McPringle** [lxndrblz/anatole#310]
**Is your feature request related to a problem? Please describe.**
For my bikepacking blog, I have a black logo with a transparent background. It is great when the light theme is active but "invisible" when the dark is active.

**Describe the solution you'd like**
I would like to specify a white version of the logo (profile picture) when the dark theme is active. E.g.:

```
[params]
profilePictureLight = 'images/profile_black.png'
profilePictureDark = 'images/profile_white.png'
```

Or maybe with the theme name in the file name:

```
[params]
profilePicture = 'images/profile_{{theme}}.png'
```

I'm open to other possible solutions.

**Describe alternatives you've considered**
I replaced the transparent parts of my logo with white color, but that looks really awful when using the dark theme.

**Additional context**
I have two versions of my logo: The original one (black on transparent) and an inverted one (white on transparent). For my personal website, I don't have this problem but I would think of adding different profile pictures, anyway. One shot of myself at daytime for the light theme, and one shot of myself at night time for the dark theme.

**Comment by lxndrblz** [comment]
@McPringle Thanks for bringing this up. Unfortunately, I think that is not possible, as we are not generating two different sites for light and dark mode but are switching the CSS classes. 

For your approach to work, we would need to generate two different versions of the site, one that has the image source set to profile_light.png and one set to profile_dark.png.

One approach you could take is to switch out the images via a bit of custom Custom JavaScript. Not perfect, but it would probably get the job done. For information on how to read and access the current "mode" please see the `anatole-theme-switcher.js`.

**Comment by McPringle** [comment]
Thanks for the explanation @lxndrblz, I understand. I have an idea which I want to try out. Maybe it works if I wrap the profile picture in an additional DIV, configure a transparent profile picture and add custom CSS to set the real profile picture as a background image to the surrounding DIV.

**Comment by McPringle** [comment]
I found a solution that worked fine for me. Maybe someone else is interested. It is very easy. I created a 1x1 pixel image where the pixel itself is transparent. I set this as the profile picture. Next, I configured the "real" profile picture as a background using custom CSS:

```css
body.theme--light img.sidebar__introduction-profileimage {
    background: url(/images/logo-light.png) no-repeat;
}

body.theme--dark img.sidebar__introduction-profileimage {
    background: url(/images/logo-dark.png) no-repeat;
}
```

It works perfectly for me and I have not found any problems so far.

**Comment by lxndrblz** [comment]
@McPringle Thanks for reporting back!
