### ISSUE TITLE
Fontawesome: Icon `fa-person-biking` not showing up in social icons

### ISSUE THREAD

**Issue by McPringle** [lxndrblz/anatole#315]
**Describe the bug**
I'm searching for an icon to represent my Komoot profile and found `fa-person-biking` suitable, which was introduced with Fontawesome 5.9 ([link](https://fontawesome.com/search?q=bicycle&s=solid%2Cbrands)). If I use this icon as a social icon, it does not show up.

**To Reproduce**
The following snippet works in `config.toml`:
```
[[params.socialIcons]]
icon = "fas fa-bicycle"
title = "Komoot"
url = "https://www.komoot.com/user/306059768140"
```

Using the `fa-person-biking` icon does not work:
```
[[params.socialIcons]]
icon = "fas fa-person-biking"
title = "Komoot"
url = "https://www.komoot.com/user/306059768140"
```

It is not a brand icon, but I tried `fab` instead of `fas` and I tried it without anything, just the icon class: The icon does not show up.

**Expected behavior**
I would expect the icon to show up next to the others.

**Screenshots**
![image](https://user-images.githubusercontent.com/1254039/155840740-b03ba390-6288-45d4-be19-8c46adb595e2.png)

**Desktop (please complete the following information):**

Tested with Chrome (Windows, macOS, Linux, ChromeOS), Firefox (Windows, macOS, Linux), Edge (Windows), Safari (macOS).

- Version of the Theme: 1.1.0 (git checkout on 2022-02-25)
- Version of Hugo: hugo v0.92.2-CDF6A0D6 windows/amd64 BuildDate=2022-02-11T14:17:39Z VendorInfo=gohugoio

**Smartphone (please complete the following information):**

Not tested on smartphones.

**Additional context**
No additional context.

**Comment by lxndrblz** [comment]
@McPringle Please update your version of the theme. About an hour ago, I have updated the theme to FontAwesome 6, which ships with the desired icon.

![image](https://user-images.githubusercontent.com/12200062/155841639-cc704919-89c6-4daa-bd9b-2a9fc172b221.png)

**Comment by McPringle** [comment]
Thank you very much for updating FA, it works! I don't know why it was a problem before, because as far as I was checking the code, FA 5.15 was used and the icon was introduced in 5.9. But it doesn't matter now, with FA 6 and serving the fonts from the own server this problem is solved for me. :-)
