### ISSUE TITLE
favicon not showing

### ISSUE THREAD

**Issue by SamEdwardes** [lxndrblz/anatole#32]
Thank you very much for creating this theme. I think it looks great and was easy to set up. I think I am experiencing a bug with the favicon.

My static folder is set up as follows:

```
static
├── CNAME
├── css
│   └── table.css
├── favicons
│   └── favicon.ico
└── img
    └── profile.png
```

config.toml looks like:

```
baseURL = "https://samedwardes.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Real Sam I Am"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = ""
author = "Sam Edwardes"
description = "Real Sam I Am - a blog by Sam Edwardes"
profilePicture = "img/profile.png"
keywords = ["sam edwardes", "blog", "outdoors", "data-science", "cycling"]
favicon = "favicons/"
customCss = ["css/table.css"]
mainSections = ["post"]
```

The favourite icon does not show up on my site [samedwardes.com](samedwardes.com):

![Screen Shot 2020-06-18 at 12 58 48 PM](https://user-images.githubusercontent.com/18248949/85066261-74f03780-b163-11ea-9a98-da8862f7e926.png)

For reference:

- [development repo](https://github.com/SamEdwardes/blog-development)
- [deployed repo](https://github.com/SamEdwardes/SamEdwardes.github.io)

Please let me know if any other info could be helpful.

**Comment by lxndrblz** [comment]
Hi Sam. Thanks for submitting your issue. I've just checked your site and the favicon shows up perfectly fine. Did you try to view the page in private mode or on another device?

**Comment by SamEdwardes** [comment]
Thank you for the quick response! Maybe it is something to do with my browser cache or other issues. I will try and clear everything and test again. But if it is working on your end I trust it is working for other visitors. 

May I suggest a PR to clarify in the documentation how to use the favicon? I would be happy to draft this. 

P.s. I am a blog/web rookie. This is only the second site I have made, the first was Jekyl / GitHub pages, so maybe this is obvious and no docs requires?

**Comment by lxndrblz** [comment]
Give it a try and let me know if it works.

A PR is always welcome! Actually, incomplete/difficult documentation is something that frustrates me about most Hugo themes. I, therefore, try not make the same mistake and explain the configuration in a way it can be understood by beginners too.

**Comment by SamEdwardes** [comment]
Thanks for the feedback Alexander. I confirm that it is now working on my browser using Google Chrome. For some reason still no luck with Firefox. Anyways not a big issue for me at this point.

![chrome](https://user-images.githubusercontent.com/18248949/85233213-7a46bf80-b3b9-11ea-89b5-b0adb225f7be.png)

![firefox](https://user-images.githubusercontent.com/18248949/85233215-7d41b000-b3b9-11ea-86c2-4bb2dcca6794.png)

I also created PR #33. It adds an example of the favicon to exampleSite, and clarifies in the README how to set up.

**Comment by lxndrblz** [comment]
Anatole also allows png based favicons:

```html
    <!-- Favicons -->
    <link rel="shortcut icon" href="{{ .Site.Params.favicon | absURL }}favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ .Site.Params.favicon | absURL }}apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ .Site.Params.favicon | absURL }}favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ .Site.Params.favicon | absURL }}favicon-16x16.png">
````

You might want to try generating those too by using [faviconit](http://faviconit.com/. ). Your favicon.ico is also quite big dimensions wise. I will add a note about this to the readme too.

**Comment by SamEdwardes** [comment]
I think you solved it. The problem was my favicon was too big, and I also did not realize you should generate different icons for different scenarios.

I ended up resizing my icon to 260x260, and then fed it through [realfavicongenerator.net/](https://realfavicongenerator.net/). I stored the resulting download in `static/favicons/`

It now works on Firefox.

![Screen Shot 2020-06-21 at 1 12 55 PM](https://user-images.githubusercontent.com/18248949/85234263-eed12c80-b3c0-11ea-9742-d164a6ebe353.png)

Thank you for your help troubleshooting this.
