### ISSUE TITLE
Google Analytics v4 requires different internal Template than currently used

### ISSUE THREAD

**Issue by vladimirdoroch** [lxndrblz/anatole#339]
**Describe the bug**
GA client script does not send proper analytics metrics to Google.
This happens if one uses the anatole template and sets a Google Analytics v4 tracking Id in the config file.

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/24272408/160679300-511623ac-43c9-4580-977d-8afacd8e3e49.png">

As shown in the picture, a client side script is run but does not send any metrics via Post ("Kein Inhalt für diese Anfrage" = "No content for request").

**To Reproduce**

1. Go to `config.toml`
2. Set `googleAnalytics = 'G-MEASUREMENT_ID'`
3. Start hugo server `hugo server -D`
4. Start a Webbrowser of choice and browse to lokal instance
5. Check `POST` messages to `google-analytics.com` via Webdev Tools of your Browser

**Expected behavior**
According to [Hugo Docs](https://gohugo.io/templates/internal/#configure-google-analytics) setting a GA v4 ID is sufficient to configure the internal template properly.

The client side GA script should transmit some metrics to Google via POST messages.
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/24272408/160679136-3149b7f9-0fc5-4277-a192-43f3f398bb53.png">

In the example above:
```
en=page_view&ep.anonymize_ip=false
en=page_view&_et=1&ep.anonymize_ip=false
en=user_engagement&_et=4818&ep.anonymize_ip=false
```

**Desktop (please complete the following information):**

- OS: macOS 12.2.1
- Browser: Safari, Firefox (doesn't matter)
- Version of the Theme: 1.8.0
- Version of Hugo: 0.95.0

**Additional context**
My current work around is a custom partial for `footer.html` which uses `_internal/google_analytics.html` template instead of `_internal/google_analytics_async.html` as specified in [Hugo Docs](https://gohugo.io/templates/internal/#configure-google-analytics).

**Comment by vladimirdoroch** [comment]
Maybe one can load the appropriate template based on the prefix of the tracking Id. 
As I understand v3 (`UA-XXXXXXX-X`) and v4 (`G-XXXXXXXX`) tracking Ids can by identified that way.

This could be catched by something like `{{ if hasPrefix . "G-"}}`. What do you think?

**Comment by lxndrblz** [comment]
@vladimirdoroch That seems like a smart solution. Feel free to send a PR and I will go ahead and merge it for you.

**Comment by vladimirdoroch** [comment]
Created pull request #341
