### ISSUE TITLE
Hide Post

### ISSUE THREAD

**Issue by kevindstevens1010** [lxndrblz/anatole#34]
Hi - I'm totally new to Hugo, is there a way to hide posts? I've added a tags section in the header, and the index page comes up.  It's not in my post folder, but it is in the content section. 

Thank you for any help and putting together this theme.

![image](https://user-images.githubusercontent.com/67278603/85638582-dfb1df00-b64b-11ea-8a0f-dac8e99b0f33.png)

**Comment by lxndrblz** [comment]
Hi thanks for reaching out.

Let me recap. You are trying to list only posts with a tag assigned but not sites?

The template that got applied on your tags page is the `list.html`. By default this template loops through all pages by using the range function.
```
  {{ range .Pages }}
```
If you wan to display only posts with a tag than that's also possible. You could simply set your menu item to link to the 'tags' page, which gets generated automatically based on the tags.

![image](https://user-images.githubusercontent.com/12200062/85774205-e78e8380-b71e-11ea-8582-750e516825e9.png)

The corresponding menu item looks like this:
```toml
  [[menu.main]]
  name = "tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"
```
In my case no other page apart from tagged posts is displayed. Is that what you wanted to achieve?

**Comment by kevindstevens1010** [comment]
That appears to have worked.  I had the full URL in listed in config. and making that change fixed it. 

Thank you!

I also have some questions around social buttons in each post for sharing.  But, I'm trying to figure these things so I don't flood the issues page.
