### ISSUE TITLE
Double H1 tag on almost every page

### ISSUE THREAD

**Issue by demaya** [lxndrblz/anatole#345]
**Describe the bug**
First: I love the theme :) Please keep the good development going. As I moved some projects to the theme and Hugo I recognized, that there are double H1 tags on almost every page. The "params.title" is used on the left pane as H1 one and if you have an blog post you have a second H1 on the page. From SEO perspective this is not very good.

See [Seobility Report](https://freetools.seobility.net/en/seocheck/check?url=https%3A%2F%2Fanatole-demo.netlify.app%2Fpost%2Fnotice-shortcode%2F&crawltype=1#h1-heading).

**To Reproduce**

* open [demo page](https://anatole-demo.netlify.app/post/notice-shortcode/)
* open dev tools
* search for `<h1>`
* see 2 appearances of h1-Tag

**Expected behavior**
Per page there should be only one h1.

Maybe we can discuss some different approaches? 2 ideas from my side:
* just style the title of the page as an h1 but use it as a span/div
* only make the title it a h1 on the homepage

**Screenshots**
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/1875832/162633060-de81584e-b20e-46f5-9731-51b2831c3937.png">

**Comment by lxndrblz** [comment]
@demaya Thanks for raising this issue. I agree, it is something that should be addressed. I think it would be best to assign a different tag to the text in the sidebar.
