### ISSUE TITLE
Weird output for code blocks with backticks on mobile

### ISSUE THREAD

**Issue by yujinyuz** [lxndrblz/anatole#346]
**Describe the bug**

The code format for codeblocks looks weird when viewing on mobile. This can be found on the demo site as well

![image](https://user-images.githubusercontent.com/10972027/163519581-da90000c-be46-4de1-aa78-d0bbbb004c48.png)

**Screenshots**

**Desktop (please complete the following information):**

- OS: iOS
- Browser Safari
- Version of the Theme
- Version of Hugo (run a `hugo version` if unsure)

**Smartphone (please complete the following information):**

- Version of the Theme
- Version of Hugo (run a `hugo version` if unsure)

**Additional context**

**Comment by lxndrblz** [comment]
@yujinyuz Thanks for raising this error. I was able to reproduce it and I am currently trying to resolve it.

**Comment by joefutrelle** [comment]
I'm seeing this in non-mobile browsers as well. Here's a screenshot from the demo site showing that most of the syntax-colored code is not rendered in a fixed-width font.

![image](https://user-images.githubusercontent.com/2365298/201166730-d239b952-78c9-4ad0-a73f-9792e518c295.png)
