### ISSUE TITLE
Link Preview

### ISSUE THREAD

**Issue by kevindstevens1010** [lxndrblz/anatole#35]
Is there a way to set a link preview for social sharing? I’d like it to show up even if there’s not an image in the post. 

I shared a post to Twitter tonight, and just the link shows up. 

Thank you!

**Comment by lxndrblz** [comment]
Hi - Unfortunately, That's something that is still on my roadmap.

https://github.com/lxndrblz/anatole/projects/1#card-38274469

However, It shouldn't be too hard to implement, as Hugo comes with a default template. See the [documentation](https://gohugo.io/templates/internal/) if you want to know how it could be implemented.

I hope to get it done within the next couple of days. 😊

**Comment by lxndrblz** [comment]
Hi there, Thanks for waiting.

Twitter Cards support is now available for all Anatole users. 🎉
Either a default image for the site or a per page image can be defined.

![image](https://user-images.githubusercontent.com/12200062/86163580-be039c80-bb10-11ea-8570-d6e4e749f91f.png)
