### ISSUE TITLE
Page doesn't pick up custom styling after being published to GitHub Pages

### ISSUE THREAD

**Issue by Xiyinx** [lxndrblz/anatole#351]
Thank you so much for this beautiful theme. This is my first time coding and using git, and your documentation has been very detailed and helpful. However, I ran into a problem which I have not been able to solve after looking through related issues like [this](https://github.com/lxndrblz/anatole/issues/64) and [this](https://github.com/luizdepra/hugo-coder/issues/160), so I decided to open this issue and any guidance will be much appreciated.

__The Issue__: 

- layouts & themes aren't loading properly after being deployed on GitHub Pages
- when run in local environment, it worked well (see screenshot below)
<img width="1333" alt="local" src="https://user-images.githubusercontent.com/104287891/164978539-822ac5e2-4f5b-49b0-9d90-8b8fd55f7328.png">

- link to the live site: https://xiyinx.github.io/xiyinsheng.github.io/
- link to my project repo: https://github.com/Xiyinx/xiyinsheng.github.io

__What I've tried__: 
 
- set `theme` in `config.toml` to be `anatole`
- set `baseurl` in `config.toml` to be `https://xiyinsheng.github.io/`
- set `data-theme` in the `index.html` to be `anatole`

Nothing's worked yet.

__Additional Context__

- I'm on Desktop
- Browser: Chrome
- Theme version: not sure. I cloned the theme directly from the link specified in the [essential steps](https://github.com/lxndrblz/anatole/wiki/1%EF%B8%8F%E2%83%A3-Essential-Steps)
- Hugo version: hugo v0.97.3+extended darwin/amd64

Looking for any guidance on how I can troubleshoot and fix this. Thank you in advance!

**Comment by lxndrblz** [comment]
Hi there,

I suspect you would need to set baseURL to https://xiyinx.github.io/xiyinsheng.github.io/ as this is where the site is currently located (the Git rep). Hop that helps.

**Comment by Xiyinx** [comment]
It worked! You are right, the problem was with the baseurl. I was confused about the difference between GitHub user pages and project pages, and thus didn't know which one to use in the `config.toml` file.

You brought good luck to me! Thank you for the super prompt reply and great help Alex. I really appreciate it.
