### ISSUE TITLE
Navigating dropdown menu displaying error

### ISSUE THREAD

**Issue by Cathrineee** [lxndrblz/anatole#352]
**Describe the bug**
When having two dropdown menus in the navigating bar, clicking on the second menu displays the first dropdown menu.

**To Reproduce**

See [my website](http://student.cs.uwaterloo.ca/~z374zhou/), when clicking on the ```Projects``` tab, the dropdown menu of ```Notes``` appears. 

My code is at <https://github.com/Cathrineee/CKive>.

**Desktop (please complete the following information):**

- OS: macOS Monterey
- Browser: chrome, safari (I've tried in both browsers and the issue occurs in both)
- Version of the Theme
- Version of Hugo (run a `hugo version` if unsure): v0.69.2

**Smartphone (please complete the following information):**

- Device: iPhone 12 ProMax
- OS: iOS 15.4.1
- Browser: safari

**Comment by guidemetothemoon** [comment]
I can look into it this week☺️

**Comment by guidemetothemoon** [comment]
The issue has now been identified and will be resolved with the PR linked above.
