### ISSUE TITLE
Navbar on mobile overflows with no scroll

### ISSUE THREAD

**Issue by codyleyhan** [lxndrblz/anatole#36]
When I add too many links to the navbar, the content overflows but does not allow for horizontal scroll/ a way to see the overflowed content.  Below is an example of what I am seeing on an iPhone X. 
![image](https://user-images.githubusercontent.com/11651981/85938463-83a4c000-b8c2-11ea-9b0b-189545a8b90a.png)

Additionally, it seems like the color change icon is on it's own line in this case.

I think ideally we would have some kind of scroll/other break here to something more mobile friendly.

**Comment by lxndrblz** [comment]
Thanks for reporting this issue! This looks indeed super ugly. 🙈
I am currently working on a Flexbox approach that will allow the menu items to overflow.

**Comment by lalabg** [comment]
Mobile example: 三 ico , click , drop-down menu . . .Is it feasible?
add submenu 
```
<menu>
<li>Red</li>
<li>blue</li>
<li>...</li>
</menu>
```
 `menu{display: none;}`
`@media only screen and (max-width: 768px) menu{  display: block; cursor: pointer;}`

**Comment by lxndrblz** [comment]
@lalabg Yes, I am fully aware that the current situation might not be fully satisfying for sites with lots of menu items.
Actually, This is something I am currently working on along with other GUI improvements (such as being able to turn off the sidebar). Bare with me just a bit longer, and I am sure I'll be able to present something slick and scalable.

**Comment by lalabg** [comment]
@lxndrblz thanks, looking forward to.
