### ISSUE TITLE
Got some errors in the last 2 versions (about after february'22)

### ISSUE THREAD

**Issue by drainuzzo** [lxndrblz/anatole#362]
**Describe the bug**
From a couple of updates ago I got this error when starting Hugo from my local Windows:

Complete message is:
```
Start building sites …
hugo v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1 windows/amd64 BuildDate=2022-05-18T11:18:14Z VendorInfo=gohugoio
WARN 2022/05/23 12:07:56 The "twitter_simple" shortcode will soon require two named parameters: user and id. See "<localsitepath>\content\post\rich-cont18:14Z VendorInfo=gohugoioent.md:26:1" 
Error: Error building site: failed to render pages: render of "page" failed: 
"<localsitepath>\themes\anatole\layouts\_default\baseof.html:8:6": executing "_default/single.html" at  _default/single.html:8:6: ex
<partial "head.html" .>: error calling partial: execute of template failed: template: _inter template failed: template: _internal/opengraph.html:37:17: executing "_internal/opengraph.html" at <index $siteSeries ($name | urlize)>: error calling index: index of untyped nil
Built in 199 ms
```

**To Reproduce**

1. Updated local Anatole repo from vscode terminal
2. Started hugo server -D
3.  Got errors

**Expected behavior**
Hugo local server stared without errors

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windos10
- Browser: any
- Version of the Theme: last 2 at least
- Version of Hugo: hugo v0.99.1 but also v0.88 (previous I had)

**Comment by lxndrblz** [comment]
The error appears to be caused by the integration of opengraph. 

Would you mind adding `series = "series"` to your taxonomy section as shown here?

https://github.com/lxndrblz/anatole/wiki/%F0%9F%93%84-Content-Settings#post-series

For further reading see:
https://github.com/lxndrblz/anatole/pull/327
