### ISSUE TITLE
Problem with Syntax Highlighting - white background

### ISSUE THREAD

**Issue by WinOpsDBA** [lxndrblz/anatole#363]
**Describe the bug**
White highlight in a code section (see screenshot)

**To Reproduce**
Install the theme as per instruction.
Test with another theme and it is working fine

**Expected behaviour**
Code highlights without white bacground

**Screenshots**
![code_higlighting](https://user-images.githubusercontent.com/48262075/170225919-7d54f87a-98eb-4911-a86f-45b316f7214e.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: crome
- Version of the Theme: 1.11.0
- Version of Hugo: v0.68.3

**Comment by WinOpsDBA** [comment]
I am new to the Hugo, please help.

**Comment by lxndrblz** [comment]
@WinOpsDBA What's the snippet that you had used?

**Comment by WinOpsDBA** [comment]
I am using it for terraform code.

**Comment by lxndrblz** [comment]
@WinOpsDBA  Hi there, I tried to reproduce your error, but only got this result:

![image](https://user-images.githubusercontent.com/12200062/170876347-df919adc-cec2-418b-9370-a73b29a81a95.png)

I had used the following snippet in the latest theme:
![image](https://user-images.githubusercontent.com/12200062/170876362-5491ffba-07ce-47ef-81d9-57e73dd24413.png)

I am wondering what you might have done differently. 🤔

**Comment by WinOpsDBA** [comment]
Good morning @lxndrblz,
Would you like to try it with monokailight, please?

my current config
```
pygmentsCodeFences = true
pygmentsUseClasses = true
customCss = ["css/syntax.css"]
```

When I look at the website generated by Hugo server I can see the following
![server](https://user-images.githubusercontent.com/48262075/172554716-d7d993fd-8713-405d-97cf-e620ae3c8a9c.png)

When I open a static website from the drive I ma getting this
![static](https://user-images.githubusercontent.com/48262075/172554956-b2900a8f-881b-4a9e-8841-2024405eef60.png)

Thank you for looking into it for me, much appreciated.

**Comment by lxndrblz** [comment]
@WinOpsDBA It seems you are loading a custom css file. Did you try the code highlighting that [comes ](https://github.com/lxndrblz/anatole/blob/master/assets/css/markupHighlight.css) with Anatole?

**Comment by martinolmos** [comment]
I have a similar issue. Bottom line is that the highlighting style is different than what is supposed to be.
I understand that the default Chroma style for Anatole is Monokailight. This is how this theme should look like according to [this Chroma style gallery](https://xyproto.github.io/splash/docs/all.html):

<img width="435" alt="image" src="https://user-images.githubusercontent.com/19807456/173242669-943f71f8-58ac-4ccf-9223-4440aad16421.png">

And this is how it looks like in my blog:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/19807456/173243367-6041540f-4765-4ce5-afb9-913801830123.png">

Looks like a total different style. Any ideas how to correct this issue?

**Comment by martinolmos** [comment]
Ok, I see in the image that you provided that the colours are correct, but the font family is different, right?

**Comment by lxndrblz** [comment]
@martinolmos Correct. This should be a serif/monospace font.
