### ISSUE TITLE
How to use table in markdown

### ISSUE THREAD

**Issue by JacksonK9** [lxndrblz/anatole#364]
**Describe the bug**
Hello
Thanks for your nice theme.
BTW, Can I use table in anatole?
When I upload to github, same markdown works well, but In anatole, It looks something weird.

![image](https://user-images.githubusercontent.com/20558677/170469243-0f5ef24e-0eb6-4113-8268-1a442b21eade.png)
![image](https://user-images.githubusercontent.com/20558677/170469266-d8807f43-da27-432b-96ab-78ca3ec0501d.png)

upper one is In anatole, lower one is in markdown preview in VSCode.

Thank you

**Comment by lxndrblz** [comment]
Hi there,

the reason why your table looks different is because Anatole currently does not ship with a style for tables and therefore tables will be styled like default HTML tables.

You can either create a custom CSS for yourself or open a PR if you want to see a specific style being added.

**Comment by JacksonK9** [comment]
Hello there.

I tried to change the style of table, But I don't know where to change.

I tried with themes\anatole\assets\scss\partials\components\_post.scss

Is this file not correct for changing these table style?

or, Do I have to delete public folder and retry to build?

Could you give me some hints for me?

**Comment by JacksonK9** [comment]
I change my config.toml and head.html, so It works for my page.

But I don't know how to Pull Request these function.

please give me some hints for Pull Requests.

**Comment by JacksonK9** [comment]
I didn't mean I don't know how to Pull Request.

I meant that I don't know where to update the anatole theme for update the css style for table.

**Comment by DonaldNA** [comment]
@JacksonK9 

I'm pretty sure you don't need to modify the scss files. Just add a custom css as detailed in the documentation [here](https://github.com/lxndrblz/anatole/wiki/%E2%9E%95-Custom-JavaScript-and-CSS).

**Comment by JacksonK9** [comment]
@DonaldNA 
Yeah, I'm already in use of custom css
I mean this is for enhancement of theme.
If not needed, I will close this issue.

**Comment by lxndrblz** [comment]
@JacksonK9 The appropriate way of adding your changes would be to create a "_table.scss" file in the vendors folder. This file would then be linked within the main.scss.

**Comment by JacksonK9** [comment]
I am trying to update the table.scss file

By the way, Can you tell me where to find how to rebuild the theme?

I changed the table.scss file, but It does not update automatically, So I want to rebuild the theme for check.

**Comment by lxndrblz** [comment]
@JacksonK9  Make sure to add it the `table.scss` to the `main.scss`. Afterwards, if you run it using hugo serve, all changes should be display automatically.
