### ISSUE TITLE
Trim the whitespace from the HTML meta tags

### ISSUE THREAD

**Issue by cedricbonhomme** [lxndrblz/anatole#366]
Would you mind if I make a PR in order to trim the whitespaces from the HTML meta tags ?
Thanks to the hyphen feature:
https://gohugo.io/templates/introduction/#whitespace

For example lines 31 and 35 here:
https://github.com/lxndrblz/anatole/blob/master/layouts/partials/head.html#L28-L39=

I have tested it, it works well.

And maybe also here:
https://github.com/lxndrblz/anatole/blob/master/layouts/partials/head.html#L2-L21=  ?

I am not that strict with whitespaces. But it looks a bit strange to me in the description meta tag.

**Comment by lxndrblz** [comment]
@cedricbonhomme Would you mind opening a PR?

Thanks.

**Comment by cedricbonhomme** [comment]
Hello, 
Yes, it's done #367 . Thanks !
