### ISSUE TITLE
Missing translation on "series" page

### ISSUE THREAD

**Issue by McPringle** [lxndrblz/anatole#369]
**Describe the bug**
Today I enabled the series taxonomy in my multi-language blog and recognized the heading "Posts in this Series" is not translated.

**To Reproduce**

1. Enabled the series taxonomy
2. Go to a blog post that is part of a series
3. Scroll down to the end of the page
4. See hard-coded text "Posts in this Series"

**Expected behavior**
I would expect to use the translation from the file `themes/anatole/i18n/xx.toml` where `xx` is the code of the actual language.

**Screenshots**

**Desktop (please complete the following information):**

- OS: all
- Browser: all
- Version of the Theme: latest from master branch today
- Version of Hugo: hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

**Smartphone (please complete the following information):**

- OS: all
- Browser: all
- Version of the Theme: latest from master branch today
- Version of Hugo: hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

**Additional context**
Translation for german (de): "Beiträge in dieser Serie"

**Comment by McPringle** [comment]
For now, I use a dirty hack that might be of interest to other users:

```javascript
/* Temporary fix for https://github.com/lxndrblz/anatole/issues/369  */
if (window.location.pathname.startsWith("/de/")) {
    document.addEventListener('DOMContentLoaded', (event) => {
        Array.from(document.getElementsByTagName("h3")).forEach(function (element) {
            if (element.innerHTML === "Posts in this Series") {
                element.innerHTML = "Beiträge in dieser Serie";
            }
        });
    });
}
```

It's not nice but at least it works (for most users, if they have JavaScript enabled on my domain).

**Comment by lxndrblz** [comment]
@McPringle Thanks for pointing this out. I agree, this should be added to the translation files.

**Comment by McPringle** [comment]
Wow, that was quick! Thank you very much!
