### ISSUE TITLE
Can I set dark mode in theme as default in config?

### ISSUE THREAD

**Issue by PiotrWachulec** [lxndrblz/anatole#38]
Link above.

**Comment by lxndrblz** [comment]
Hello Piotr, thanks for your inquiry.

Right now there is no simple way of setting the dark theme as the standard in the the config. However, it can still be accomplished with some manual tweaking.

You would need to patch this condition in the `anatole-header.js`.

```
    if (theme === null) {
        if(userPrefersDark){
            setTheme('dark');
        }
        else{
            setTheme('light');
        }
    }
```

To something more like this:
```
  if (theme === null) {
            setTheme('dark');
    }
```
What is different here is that the original function takes in account if a user has darkmode enabled prefers the light version of the theme. 

I’m not planning on changing this to be configured through the `config.toml`, but it’s a great suggestion and contributions are always welcome!

**Comment by PiotrWachulec** [comment]
Hello @lxndrblz ! Thanks a lot for really quick and expanded answer! :) I'm not planning to hack it manually :) Thanks again!

**Comment by lxndrblz** [comment]
@PiotrWachulec  I will reopen this issue and it to the project roadmap. I think a lot of users could benefit from this.

**Comment by PiotrWachulec** [comment]
Really great! ;) Thanks @lxndrblz ;)
