### ISSUE TITLE
Please create a partial for ToC

### ISSUE THREAD

**Issue by jaestevan** [lxndrblz/anatole#380]
**Is your feature request related to a problem? Please describe.**

Not having a partial for ToC it is impossible to customize the markup on my posts

**Describe the solution you'd like**

Change `single.html` file to use a `partial` template file for `.Params.toc`, as it's doing with series or related posts.

**Comment by lxndrblz** [comment]
@jaestevan It is already implemented. You can activate by setting `.Params.toc` to true.

**Comment by jaestevan** [comment]
> @jaestevan It is already implemented. You can activate by setting `.Params.toc` to true.

What I mean is at file https://github.com/lxndrblz/anatole/blob/v1.9.0/layouts/_default/single.html, line 45

      {{- if (eq .Params.toc true) -}}
        <h3>Table of Contents</h3>
        {{ .TableOfContents }}

There is no use of a partial template, like for example at line 54

      {{- if isset .Params "series" -}}
        {{- partial "series.html" . -}}

And then there is no option to create a partial template file to customize the ToC output without modifying the theme files. For example to remove or translate this <h3> tag hardcoded in the single.html file.

Hope that helps clarify.

Thanks!
JA.

**Comment by jaestevan** [comment]
@lxndrblz I sent a pull request with a very small change to fix this issue.

I think I also included what I was expecting to be a different PR. Sorry about that, still new with GitHub. Still I think this second change is also simple but useful.

Thanks,
JA.

**Comment by lxndrblz** [comment]
@jaestevan Hi there, I've opened a separate PR for your other adjustment. Please only do one topic at a time.
