### ISSUE TITLE
Broken print layout

### ISSUE THREAD

**Issue by Sohn123** [lxndrblz/anatole#387]
**Describe the bug**
The print version of the pages look broken. The sidebar interferes with the content. 

**To Reproduce**
Go to the home page and press `ctrl+p` and take a look at the layout. 

**Expected behavior**
A concise print layout.

**Screenshots**
![image](https://user-images.githubusercontent.com/39831045/193625585-71aff18e-7dd2-4d3e-b8bb-7424ce1fc925.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser firefox,chrome
- Version of the Theme latest master
- Version of Hugo hugo v0.104.2+extended

**Smartphone (please complete the following information):**

- Version of the Theme
- Version of Hugo (run a `hugo version` if unsure)

**Additional context**

[example_print.pdf](https://github.com/lxndrblz/anatole/files/9699088/example_print.pdf)

**Comment by Sohn123** [comment]
I took a quick look today, and it seems like the root cause of the problem is that the desktop style gets partly applied to the print layout. By removing the mixedin `desktop_and_print` and just using `desktop` instead, the print layout appears to be fixed.

**Comment by lxndrblz** [comment]
@Sohn123 Can you send me a PR with your changes?
