### ISSUE TITLE
Error when try to update

### ISSUE THREAD

**Issue by erbaafidotama** [lxndrblz/anatole#393]
Hello.
Thanks for make amazing hugo theme. I use anatole for my personal blog.

**Describe the bug**
I try to update my anatole theme with run this command in my terminal.
`hugo mod get -u github.com/lxndrblz/anatole`
but it showing error:
`go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.`

**To Reproduce**
Run `hugo mod get -u github.com/lxndrblz/anatole` in terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/22489268/197325123-c87e53a8-910d-42a8-8f0c-2da19942a9a0.png)

**Desktop (please complete the following information):**

- OS: Linux (Zorin OS 16,2)
- Version of the Theme
- Version of Hugo (run a `hugo version` if unsure)

**Smartphone (please complete the following information):**

- Version of Hugo: Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z

Thanks.

**Comment by lxndrblz** [comment]
@lxndrblz Can you please confirm that you executed the command in the correct directory? Based on the error message it sounds as the mod go.mod file could not be located.

**Comment by erbaafidotama** [comment]
go.mod? Sorry, Am i must run `go mod init` before update?

**Comment by erbaafidotama** [comment]
This problem solved, with run `go mod init`.
Thanks @lxndrblz
