### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by msfjarvis** [lxndrblz/anatole#4]
This should be rather straightforward to implement with CSS3 variables and the `prefers-color-scheme` media query. I'd personally also love for there to be a user-facing toggle since some platforms don't support the `preferes-color-scheme` query. For that purpose I have put together a bit of [JS](https://github.com/msfjarvis/msfjarvis.dev/blob/730e1e7a0f0c6374f475b8dfd34f13bcf878969d/assets/js/theme-switcher.js) and [CSS](https://github.com/msfjarvis/msfjarvis.dev/blob/730e1e7a0f0c6374f475b8dfd34f13bcf878969d/assets/css/custom.css#L48-L63) in my site for the manual toggle to work. If I am able to adopt this theme to my site I'd love to contribute this feature.

**Comment by lxndrblz** [comment]
Hello Harsh, thanks for your suggestion; it's highly appreciated. I've added this to the theme's [roadmap](https://github.com/lxndrblz/anatole/projects/1).

A while back, I also thought about it and did some initial research and it doesn't look too hard. Please feel free to contribute to the theme, if you got it working on your personal site.
