### ISSUE TITLE
Use monospace font for code blocks

### ISSUE THREAD

**Issue by ericswpark** [lxndrblz/anatole#406]
**Describe the bug**
Because the current font used within code blocks has variable width, it messes up formatting if lines reference each other, such as output from a compiler highlighting a bug within a line, for example.

**To Reproduce**

1. Create a code block
2. View in browser

**Expected behavior**
Code blocks should not use variable width font

**Screenshots**
Red arrows indicate where the caret should've been shown:
![3DB7F7C3-FCE4-4B5E-88F3-D862E2C18E48](https://user-images.githubusercontent.com/13326074/205418445-44b0a7cc-02f7-407f-b92e-bdba29bdc55b.jpeg)

**Comment by lxndrblz** [comment]
This issue seems to be related to issue #346.

**Comment by mike-kfed** [comment]
I fixed the problem by replacing the wildcard `* {}` selector with `body {}` in `assets/scss/partials/_base.scss`. Since I don't know why wildcard is used in the first place I am not sending a PR, this potentially breaks other stuff, works for me however :)

**Comment by lxndrblz** [comment]
@mike-kfed That's a good observation. Would you mind sending a PR with your changes? I could then verify if it has any other side effects or what's the best approach of resolving this quite annoying issue.

**Comment by xjasonlyu** [comment]
For anyone who needs it, here's a temporary workaround:

- simply put this in your `assets/css/custom.css`

```css
* {
    font-family: inherit;
}

body {
    font-family: 'PingHei', 'PingFang SC', 'Helvetica Neue', 'Work Sans', 'Hiragino Sans GB', sans-serif;
}
```
