### ISSUE TITLE
lang="{{- site.Language.Lang -}}"

### ISSUE THREAD

**Issue by lalabg** [lxndrblz/anatole#41]
I seem to have missed something
hugo v7.0+ 
`lang="{{- site.Language.Lang -}}"`
languageCode = "sg","de","ly"
forever
`<html lang="en" data-theme="light">`

**Comment by lxndrblz** [comment]
Hi there,

in order to set the language code to `de` globally, you would need to configure the `DefaultContentLanguage` as it defaults to `en`. 🚩

The `languageCode` only affects the RSS generation and multi language setups. 

https://gohugo.io/getting-started/configuration/

**Comment by lalabg** [comment]
thanks, You\'re absolutely right.
