### ISSUE TITLE
work not correctly on github-pages

### ISSUE THREAD

**Issue by landaal-ict** [lxndrblz/anatole#412]
**Describe the bug**

Hosted on github pages 
[Imgur](https://imgur.com/zwoEOlh)

When the site is hosted local:
[Imgur](https://imgur.com/9iKgtj0)

So when host local or on an appache2 or nginx server al the icons show correcly.
when the page is hosted on github pages all the icons en social icons are gone.

anyone a solution?

**Comment by lxndrblz** [comment]
@landaal-ict Can you please send me the link of the faulty page?

**Comment by landaal-ict** [comment]
yes its here https://landaalict.nl/
When i hun localhost everthing is fine.

**Comment by lxndrblz** [comment]
This is due to an integrity check error:

![image](https://user-images.githubusercontent.com/12200062/210045154-cd211d09-e558-47c3-9c76-b8ca0e032224.png)


We had a similar issue before in #114 . Can you check if the solutions work for you?

**Comment by landaal-ict** [comment]
yes thnx for the help!

i removed the theme
set my line endings
```
git config --global core.autocrlf input
```
that fixt the problem

![image](https://user-images.githubusercontent.com/89043910/210053505-71c7b14f-3312-45b7-99a7-6becc636c301.png)
