### ISSUE TITLE
Disappearing posts from home page

### ISSUE THREAD

**Issue by PiotrWachulec** [lxndrblz/anatole#42]
Hi @lxndrblz ,

I'm trying to add Disqus comments on my website with your theme. I have a website configured like in an example site. When I added Disqus shortname in the config and in my posts I added `type: "post"` (like [here](https://github.com/lxndrblz/anatole/issues/3)), the comments section in posts was visible, but all posts with this markup disappeared from the home page. You can observe it on my [website](https://devdiary.wachulec.me/).

Could you help me with that issue?
Thanks in advance!

**Comment by PiotrWachulec** [comment]
I fixed it - folder with posts have to name **post**, not **posts**. Then even adding `type: post` is unnecessary.

**Comment by lxndrblz** [comment]
I want to add some additional information to the linked issue #3 as some things have changed over time. The disqus comments are displayed if the type is "Post".  A new post can be created by:
```
hugo new post/mynewpost.md
```
The content displayed on the frontpage can be controlled through:

```toml
[params]
  mainSections = ["post", "docs"]
```
Like you noted, in the `exampleSite` this is also set to `post` (no plural).

Hope that makes sense.

**Comment by PiotrWachulec** [comment]
Thanks for additional explanation. I tested it on my own and now I know how it works and how it should be configured :)
