### ISSUE TITLE
Show post contents in a post page

### ISSUE THREAD

**Issue by AcademicusChamaeleon** [lxndrblz/anatole#426]
**Is your feature request related to a problem? Please describe.**
I tried to use a static home page and show post contents (or a few lines and read more) on a post page, but it seems it only has a achiece type layout.

**Describe the solution you'd like**
I would like a static home page and show post contents (or a few lines and read more) on a post page.

**Comment by lxndrblz** [comment]
Please see the [Wiki](https://github.com/lxndrblz/anatole/wiki/%F0%9F%93%84-Content-Settings#using-a-static-page-as-your-home-page) for how to set up a static home page.
