### ISSUE TITLE
Any plans to support older browsers?

### ISSUE THREAD

**Issue by ericswpark** [lxndrblz/anatole#430]
The README doesn't explicitly state this as a feature, but are there any plans to support old browsers? For example, on old iOS Safari (9.3.5), I found that the hamburger dropdown doesn't work at all.

EDIT: For some reason this submitted as a blank issue, sorry! I think it's because I clicked on the "New Issue" button while not logged in and it skips the issue chooser screen.

**Comment by lxndrblz** [comment]
@ericswpark No, this is not a priority currently.
