### ISSUE TITLE
Setting missing from wiki page

### ISSUE THREAD

**Issue by gummigroda** [lxndrblz/anatole#435]
**Describe the bug**
There is a setting called `reversepagetitle` and with the move of the docs to the wiki this seems to have fallen out.

**To Reproduce**

1. Check old README.md at https://github.com/lxndrblz/anatole/pull/303/files# . Click on '....'
2. Scroll to row 797

**Expected behavior**
Setting to be documented in the wiki

*(I was unable to create a PR for the wiki repo, as this functionality is missing in GitHub without workarounds.)*

**Comment by lxndrblz** [comment]
@gummigroda Thanks for spotting this. I've added it to the wiki.

https://github.com/lxndrblz/anatole/wiki/%F0%9F%92%85-Appearance
