### ISSUE TITLE
Adding things like "1 minute read" and date inside the blog post

### ISSUE THREAD

**Issue by auroraongithub** [lxndrblz/anatole#438]
I managed to figure out how to finally make a blog post and customizing my page after like 3 hours due to the lack of documentation, so now I'm trying to do the finishing touches. How do I get the estimated post read length and the date IN the blog post? It doesn't seem to show. No matter how mcuh I dig through the example site files, I can't find it. (not to sound rude, i love your theme)

![image](https://user-images.githubusercontent.com/86182778/227775425-18f10574-7eda-4e15-b959-2d8ffef064a2.png)

**Comment by auroraongithub** [comment]
also i'm wondering how to publish this to github pages, i've spent 5 hours on this now XD

**Comment by ericswpark** [comment]
@auroraongithub I believe the read estimate and date only shows up for post page types, not single page types.

**Comment by auroraongithub** [comment]
> @auroraongithub I believe the read estimate and date only shows up for post page types, not single page types.

i see, i dont get it but it is what it is, do you have an idea how i can put this on github pages? i'm really trying rn but it doesn't work 

![image](https://user-images.githubusercontent.com/86182778/227781903-76bc5328-7afb-4077-b04b-69412463f27c.png)

i think i managed to get most of the folders from my local folder to github thru terminal but it doesn't look like the theme in my themes folder was included

**Comment by eclecticpassions** [comment]
@auroraongithub: @ericswpark 's answer means that for the read time to show up, you have to type `type = 'post'` in the front matter of your post (between the two `+++`). If you do that, the date and read time estimate will show up.
