### ISSUE TITLE
Questions about Table of Contents

### ISSUE THREAD

**Issue by wrysunny** [lxndrblz/anatole#440]
I have set the parameter "toc = true" in the params.toml file located in the "config/_default" directory of my website's root directory. However, when I access my website, the Table of Contents is still not being displayed. The only issue I could find related to this is on https://github.com/lxndrblz/anatole/issues/131. Do I need to follow the instructions provided in that issue, or is there another configuration parameter that I need to set?

**Comment by lxndrblz** [comment]
The toc needs to be enabled in the frontmatter of a post. This can't be done globally.
