### ISSUE TITLE
Misaligned first code line in code blocks

### ISSUE THREAD

**Issue by xjasonlyu** [lxndrblz/anatole#447]
Taking the demo site as an example, the first line in the code block is slightly misaligned compared to the rest:

<img width="477" alt="Screenshot 2023-04-17 at 11 19 10 PM" src="https://user-images.githubusercontent.com/28824352/232532941-389d8bc7-8b13-4672-a1e0-0e5f90230fdd.png">

This issues applies to all the clode blocks and styles too.

**Comment by xjasonlyu** [comment]
The issue seems to be caused by this css layout:

https://github.com/lxndrblz/anatole/blob/1ac45419dcc725d4af83a411b94997370fd56d70/assets/scss/partials/components/_post.scss#L76-L85

the `2px` padding and `1px` border were combined and added to the head and tail of the code block, which contributes to this misaligned layout.

**Comment by lxndrblz** [comment]
@xjasonlyu Is this issue still current?

**Comment by xjasonlyu** [comment]
Yes, it still exists.
