### ISSUE TITLE
can the page be divided into two columns?

### ISSUE THREAD

**Issue by 7-qiliu** [lxndrblz/anatole#46]

**Comment by lxndrblz** [comment]
Hi there,


Thanks for your issue. Would you mind specifying your exact need? A screenshot would be helpful too.

Alex

**Comment by 7-qiliu** [comment]
Hi @lxndrblz 

thanks for your kind reply. The exact need for two-column layout is that left side contains the image, and right side contains the text.The example screenshot is shown below:
<img width="1066" alt="screenshot_two_column" src="https://user-images.githubusercontent.com/51437250/88313112-9b4a5980-cd45-11ea-9087-1bc04c7b3882.png">

When viewing in the phone, it would become two-row layout:
<img width="482" alt="screenshot_two_row" src="https://user-images.githubusercontent.com/51437250/88313661-6db1e000-cd46-11ea-93d4-c3da5c0e01b4.png">

Note: the images are borrowed from [hugo-casper3](https://hugocasper3-demo.jonathanjanssens.com/)

**Comment by lxndrblz** [comment]
Gotcha. Are you looking for this kind of style for only image descriptions or other content as well? 

I really like how Casper handles the image descriptions. It looks really good. Might be worth adding such an approach to the project map.

**Comment by 7-qiliu** [comment]
@lxndrblz yeah, I'm looking for this kind of style for image descriptions. The adaptive window looks comfortable :D

**Comment by lxndrblz** [comment]
@7-qiliu Sorry for the wait, I'd a closer link at the theme you provided as a reference.

They are using the images as a blog post image and not just nicely styled figures within blog posts (like I thought initially). As Anatole, unlike Casper3 focuses on a text first experience, I don't really see a need for integrating the ability to have thumbnails on the front page. I'll therefore go ahead and close the issue, as I (currently) don't see a need for it.
