### ISSUE TITLE
Wiki: Add missing parameter to Umami Analytics

### ISSUE THREAD

**Issue by tbrixen** [lxndrblz/anatole#468]
The PR https://github.com/lxndrblz/anatole/pull/418 added the ability to override the script name for Umami Analytics. Unfortunately, the [Wiki on Analytics](https://github.com/lxndrblz/anatole/wiki/%F0%9F%93%88-Analytics#adding-umami-analytics) wasn’t updated.

After the PR change, this even works with the cloud offering. The current wiki only mentions self-hosted.

An example of using the cloud version. 

```bash
[params.umami]
serverURL = "analytics.umami.is"
id = "94db1cb1-74f4-4a40-ad6c-962362670409"
trackerScriptName = "script.js"
```

**Inspirational text**

To use Umami Analytics, include the following section and change the `id` to the Website ID from Umami. If you self-host Umami, also change the `serverURL` and `tracerScriptName` to fit your installation.

```bash
[params.umami]
serverURL = "analytics.umami.is"
id = "94db1cb1-74f4-4a40-ad6c-962362670409"
trackerScriptName = "script.js"
```

**The current wording**

To use Umami Analytics, include the following section and change the `serverURL` to your self-hosted Umami server URL. Additionally, you will need to provide your website ID.

```bash
[params.umami]
serverURL = "example.com"
id = "94db1cb1-74f4-4a40-ad6c-962362670409"
```

**Comment by lxndrblz** [comment]
@tbrixen Thanks for your suggestions. I have updated the wiki section accordingly.

https://github.com/lxndrblz/anatole/wiki/%F0%9F%93%88-Analytics
