### ISSUE TITLE
Description in Yaml. Rmd Files.

### ISSUE THREAD

**Issue by amosino** [lxndrblz/anatole#47]
Hello. I'm adding some description in the yaml metadata of my posts. However, the default summary is still being shown in my site instead of my description. **I'm writing .Rmd files**. Why I'm doing wrong?

This is the metadata I'm using:

---
title: Some Title
author: Me
date: '2020-07-24'
description: 'This is a description.'
  
slug: Some slug
categories:
  - C1
  - C2
tags:
  - T1
  - T2
weight: x
---

This is my post.

Thanks,

Alejandro

**Comment by lxndrblz** [comment]
Hello Alejandro,

I have a very little with rmd, but let's have a look. 😊

Did you try to use the summary option in the frontmatter rather than description?

Alex

**Comment by amosino** [comment]
Hello Alex,

It's kind of weird. I use the summary option as suggested, and everything seems to be rendering just OK on R Studio Viewer. However, when I serve the site to GitHub and viewing it on the web (using Netlify), no description (but the first lines of the post) is shown.

Alejandro

**Comment by lxndrblz** [comment]
Alejandro,

Thanks for the clarification. I am currently away from my PC, but I'll try to reproduce it. I don't see any reason why it should ignore your summary from the frontmatter.

Mind checking one last thing: Does the site look correct if you create it locally? Or is the error already there?

Aldx

**Comment by amosino** [comment]
When I used description I had an error both locally and on the web. Now, with summary, everything seems to be ok locally but not on the web.

Thanks again!

**Comment by lxndrblz** [comment]
@amosino  Thanks for your patient and your feed back. Something that is important with Netlify and RStudio is that you specify the correct Hugo version. Can you try executing a `blogdown::hugo_version()` and setting this as a new variable for your Netlify site (Key = HUGO_VERSION and Value = 0.XX.X)?

**Comment by amosino** [comment]
Hello Alex,

As suggested, I set the hugo version on Netlify. But everything seems to be the same. No correct summary on the web :(.

**Comment by amosino** [comment]
Oh no, wait! I think that was a matter of time. It finally worked after those changes!!!!

Thank you very much!
