### ISSUE TITLE
Can't add CC licence HTML code in the copyright parameter in Hugo.toml

### ISSUE THREAD

**Issue by eclecticpassions** [lxndrblz/anatole#476]
**Problem**
I can't seem to get html code to work in the `copyright` parameter of hugo.toml, only plain text.

**Describe the solution you'd like**
I want to paste the html license code created from Common Creative's [site](https://chooser-beta.creativecommons.org/) into the `copyright` parameter so it will show up on the bottom of sidebar.

**Describe alternatives you've considered**
I found a workaround, which is to paste the html code into the `description` paramater, but then I can't `copyright = false` to hide the bottom line with the © symbol in the sidebar.

Thanks!

**Comment by lxndrblz** [comment]
Hey @eclecticpassions,

Unfortunately, this is currently not possible. The only work around would be to overwrite the relevant `footler.html` section.
