### ISSUE TITLE
Theme not rendering properly

### ISSUE THREAD

**Issue by jwalsh2me** [lxndrblz/anatole#48]
Did something change in the last build or two?  I did the following:

```
git clone https://github.com/lxndrblz/anatole.git anatole
cd anatole/exampleSite
hugo server --themesDir ../..
```

I do not get a functioning site, instead I get this:

<img width="423" alt="Screen Shot 2020-07-27 at 8 22 22 PM" src="https://user-images.githubusercontent.com/22819585/88608660-e4e9bb80-d047-11ea-8606-250b4775807d.png">

Did something break in the last few merges?  I was able to do this a few weeks ago, but when I newly cloned the repo this happened.

**Comment by lxndrblz** [comment]
Hi John,

Indeed, That looks uggly. It looks like we are having either a simple caching issue or the css might not be linked correctly. Inorder to narrow down the problem, would you mind checking the following:

- Try using a different browser or private mode and check if it looks like it's right now.
- Can you check with the inspector if your css is linked correctly in the header (also try to follow the links)?
- Did you get any errors in the console?

The only thing that did change in the past is the way custom css is handled. It's now modified by Hugo and served from a different directory. Did you have custom css?

Alex

**Comment by jwalsh2me** [comment]
Hi Alex,

I will try a new site local and load the theme.  Brew also jus update my Hugo version to 0.74.3.

John

**Comment by jwalsh2me** [comment]
OK did the following:

```
 hugo new site test-blog
cd test-blog
git clone https://github.com/lxndrblz/anatole.git anatole
cd anatole/exampleSite   
hugo server --themesDir ../..   
```

Same rendering error, seeing CORS issues blocking localhost to the CSS.

<img width="1233" alt="Screen Shot 2020-07-28 at 8 18 02 AM" src="https://user-images.githubusercontent.com/22819585/88670734-0cbe3b00-d0ab-11ea-8e6e-fc1974b36ecb.png">


However clicking the links, the posts render and look fine:  http://localhost:1313/post/rich-content/

Thank clicking the links, Home, Posts, About look good.

Do you think it was a browser cache issue, or possibly Hugo 0.74.2?

**Comment by lxndrblz** [comment]
@jwalsh2me  I am having a hard time reproducing this issue, due to access to a Mac with Safari, but we are getting there. What I did notice is that the same error occurs when trying to access the localhost IP "127.0.0.1". Once you click on something it goes to "localhost" and then CORS works correctly. Can you please try to use `http://localhost:1313` rather than the IP version?

**Comment by jwalsh2me** [comment]
Ah!  Yes, will give that a try.  That would explain it.

**Comment by jwalsh2me** [comment]
@lxndrblz That did it... So it is a CORS issue with `127.0.0.1` versus `localhost`. Good catch, missed that redirect to localhost.  Guess it is not really a bug, as looking at Hugo they do say to connect to `http://localhost:1313/`
