### ISSUE TITLE
I can't change my profile picture.

### ISSUE THREAD

**Issue by tangxuemei1995** [lxndrblz/anatole#49]
I have put my picture in [images] dictionary, I changed the path of profile picture in [config.toml].
 but when I open the web http://localhost:1313/, I can't see the picture.why?

**Comment by lxndrblz** [comment]
@tangxuemei1995  I'm sorry you are having trouble getting the image to show up.

In understood that you put the image into the 'static/images' folder.
To help you narrow down the problem, I need a little bit more information:

- Could you please provide me a snippet of your 'config.toml' that shows the relevant section?
- Dou you get any errors in your browser/hugo console?
- May I also know, which file format you tried to use?

**Comment by tangxuemei1995** [comment]
thanks for your reply.
when I use the original picture, it can't display normally, is this the problem of my browser.i use chrome.

I put my picture in 'static/images'. it's  'jpeg'.
<img width="289" alt="WechatIMG736" src="https://user-images.githubusercontent.com/40517398/89004607-22469580-d335-11ea-9ab0-18c39f54d8a8.png">

and I change the path:
<img width="253" alt="WechatIMG737" src="https://user-images.githubusercontent.com/40517398/89004637-37bbbf80-d335-11ea-96e7-4361746de4ae.png">

when I open  http://localhost:1313/, it like this:
<img width="439" alt="WechatIMG738" src="https://user-images.githubusercontent.com/40517398/89004677-4dc98000-d335-11ea-85dc-3e517a7836e6.png">

I don't know what the problem is.

**Comment by lxndrblz** [comment]
@tangxuemei1995 Thanks for the screenshots.  I think I've found your problem. :)

You have to put the the `my.jpeg` inside the `static/images` of your "main" hugo folder. The exampleSite is only include as a quickstart to copy some default data. Also make sure you make the configuration changes to your `config.toml` in the main folder and not the `exampleSite`.

Your whole project structure should look like this:
```
C:. tangxuemei1995
├───config.toml (Your config.toml goes into here)
├───archetypes
├───assets
│   └───js
├───content
│   └───post
├───data
├───layouts
├───static
│   ├───css
│   └───images (Your image goes into here)
└───themes
    └───anatole
        ├───.github
        ├───archetypes
        ├───assets
        │   ├───css
        │   └───js
        ├───exampleSite
        │   ├───content
        │   │   └───post
        │   └───static
        │       ├───favicons
        │       └───images
        ├───images
        ├───layouts
        │   ├───custom
        │   ├───partials
        │   │   └───taxonomy
        │   └───_default
        └───static
            ├───css
            └───images
```
Let me know if this resolved your problem.

**Comment by tangxuemei1995** [comment]
thanks, with your advice, I solved my problem. :)
