### ISSUE TITLE
BlueSky social logo — upgrade FontAwesome to latest release (6.5.2)

### ISSUE THREAD

**Issue by andihindle** [lxndrblz/anatole#504]
**Is your feature request related to a problem? Please describe.**

The latest release of FontAwesome (6.5.2) includes (amongst other things) the BlueSky social logo, which I'd like to be able to use.

**Describe the solution you'd like**
Upgrading to 6.5.2 should then allow "icon = "fab fa-bluesky" in config to work.

**Describe alternatives you've considered**
none applicable

**Additional context**
I considered trying the suggestion proposed in issue #80, but I think the structure has changed since that suggestion was made.

**Comment by thomjak** [comment]
Would be great to get this updated. Thanks for an awesome theme!
