### ISSUE TITLE
Mutlitlingual mode

### ISSUE THREAD

**Issue by Sohn123** [lxndrblz/anatole#52]
I tried to acitvate the multilingual mode with the description in the readme, but it didn't work. In addition to the changes to config.toml suggested there, I had to specify a base directory to get the multilingual mode working. If this is in general so, the readme should be adapted accordingly.

**Comment by lxndrblz** [comment]
@Sohn123  Good catch. There are two ways of translating your content either by a suffix in the filename eg. `mypost.de.md` or by setting a `contentDir` for each language. I assume you used the latter option.

Nevertheless, I will add a few pieces of additional information to the readme to make this more clearly.

**Comment by Sohn123** [comment]
Now it works like a charm. Thanks for the great theme!
