### ISSUE TITLE
Summary of posts are missing on index page with Hugo versions 0.134.0 and newer.

### ISSUE THREAD

**Issue by McPringle** [lxndrblz/anatole#529]
**Describe the bug**

In the past, the index page (home page) of my blog showed a post summary between the post title and the read more link. Since newer versions of Hugo (v0.134.0 and newer) the summary is not rendered any more on the home page. Please see the attached screenshots, where I rendered the same source with Hugo v0.133.1 and v0.134.0.

**To Reproduce**

Create a website which displays a summary of each post on the home page. Render the website using Hugo v0.133.1 and Hugo v0.134.0. Compare both websites.

**Expected behavior**
I expect the summary to be shown when rendering the same website using a newer Hugo version.

**Screenshots**
Rendering with Hugo v0.133.1:
![image](https://github.com/user-attachments/assets/8b9d8cf2-692c-4444-aa93-86598b2c592e)
Rendering with Hugo v0.134.0 and newer:
![image](https://github.com/user-attachments/assets/83723017-c2da-4d11-8817-e147ed1e6e8e)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: all
- Version of the Theme: v1.16.0
- Version of Hugo: v0.140.0 (tried v0.133.1 and v0.134.0, too)

**Smartphone (please complete the following information):**

I didn't tried it with a Smartphone.

**Additional context**

I did not overwrite, replace, or modify the theme files in any way.

In the [release notes of Hugo v0.134.0](https://github.com/gohugoio/hugo/releases/tag/v0.134.0) I found something about a (citation) *slightly breaking change* regarding the content summary handling.

**Comment by McPringle** [comment]
Analyzing the HTML I found the following comment in the output files generated by Hugo v0.134.0+:
![image](https://github.com/user-attachments/assets/723c1af6-69b9-4df8-b9d1-6dc8fa3ec2f9)

**Comment by McPringle** [comment]
Hugo uses Goldmark to render Markdown to HTML. Goldmark marks HTML in Markdown files unsafe. Regarding the release notes of Hugo v0.134.0 the summary is now HTML, not markdown (if I understand it correctly). So Goldmark tries to render Markdown, which in reality is HTML, and replaces the HTML with the unsafe warning comment.

A quick and dirty workaround is to configure Goldmark using `hugo.toml` to allow unsafe HTML:

```toml
[markup.goldmark.renderer]
unsafe = true
```

This is a dirty hack because Goldmark should not be called with HTML code. I'm not familiar with Hugo template programming, but I think the pipe in the followin code is the problem:

![image](https://github.com/user-attachments/assets/1fdda023-5f88-4723-b4ff-4e5a27c3e91d)
https://github.com/lxndrblz/anatole/blob/master/layouts/index.html#L60C28-L60C39

**Comment by lxndrblz** [comment]
@McPringle I'll have to look into this. Thanks for bringing this to my attention.

**Comment by McPringle** [comment]
Works like a charm, thank you very much for fixing it so quickly!
