### ISSUE TITLE
Floating Images and Shortcodes

### ISSUE THREAD

**Issue by Gregory-Gelfond** [lxndrblz/anatole#59]
This isn't an "issue" per-se but more of a question. I understand that if I use shortcodes for figures within a post, like in the following example:

```
{{< figure src="/images/comics/explorers.jpg" >}}

paragraph text
```

the image will be positioned centered and above the paragraph text.

I'm curious if it's possible to position the image to the right of the paragraph (and possibly have the paragraph text wrap/flow around the image?

Also, I was unable to figure out how to position two images side by side.

Any help would be appreciated.

**Comment by lxndrblz** [comment]
@Gregory-Gelfond Thanks for your question.

It depends a bit what you want to achieve. If you want image to be always placed to the left/right than that could be achieved via some custom css.

If you want to have a fine control, of how individual images are placed than you might want to use short codes. See the [documentation](https://gohugo.io/content-management/shortcodes/#example-figure-input) for an example. That way it would always look uniform (assuming you have the necessary css in place which should be fairly easy).

Custom short codes are something I personally find quite important too and that's why I had added it to the project map. I hope to get it merged to the master soon. This also involves resolving the other open issue.

**Comment by Gregory-Gelfond** [comment]
Thanks for the response - I have to admit I’m new to html/css, and some googling didn’t particularly help.

Is this along the lines of what you seem to be suggesting?

https://jpescador.com/blog/leverage-shortcodes-in-hugo/
On Aug 20, 2020, 10:25 AM -0500, Alexander Bilz <notifications@github.com>, wrote:

@Gregory-Gelfond<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Gregory-2DGelfond&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=hLDlTRxSe6uc8J-voA79NLz4ycd0Zj49_1Jn-MqewPg&m=L3VuVEVtMu3MIO-UIxGotstt2uHpay_0mzIgSfSG3eU&s=iHQ4Ej3hsr4qf4_Txjbi125cIxQmOaQSDxLi3-zcbyk&e=> Thanks for your question.

It depends a bit what you want to achieve. If you want image to be always placed to the left/right than that could be achieved via some custom css.

If you want to have a fine control, of how individual images are placed than you might want to use short codes. See the documentation<https://urldefense.proofpoint.com/v2/url?u=https-3A__gohugo.io_content-2Dmanagement_shortcodes_-23example-2Dfigure-2Dinput&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=hLDlTRxSe6uc8J-voA79NLz4ycd0Zj49_1Jn-MqewPg&m=L3VuVEVtMu3MIO-UIxGotstt2uHpay_0mzIgSfSG3eU&s=lQinvwvYWdSdtFQUpZfDckkGgGil-RcBTjxMajEOAiw&e=> for an example. That way it would always look uniform (assuming you have the necessary css in place which should be fairly easy).

Custom short codes are something I personally find quite important too and that's why I had added it to the project map. I hope to get it merged to the master soon. This also involves resolving the other open issue.

**Comment by lxndrblz** [comment]
@Gregory-Gelfond yes, that's how the short codes would look like. However, you'll still need a bit of CSS to make everything pretty and functional.

**Comment by lxndrblz** [comment]
@Gregory-Gelfond Sorry for the wait. Is that what you were trying to achieve?

![image](https://user-images.githubusercontent.com/12200062/91329852-f51cc400-e7c8-11ea-9a15-e8d5e590b489.png)

**Comment by Gregory-Gelfond** [comment]
That's exactly what I'm hoping to have at some point. This is fantastic.

**Comment by rsln-s** [comment]
+1 to this issue. Would love to see support for this, especially on the front page (i.e. having images in the short preview), like this:
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/11508369/92664211-5c5e6c00-f2d1-11ea-8942-1773675769e7.png">

**Comment by lxndrblz** [comment]
Reopened this issue upon request by @Gregory-Gelfond.

**Comment by lxndrblz** [comment]
@Gregory-Gelfond  I've implemented the feature as requested. The shortcode code [example](https://github.com/lxndrblz/anatole/blob/master/exampleSite/content/post/figure-shortcode.md) will give you something like this:

![image](https://user-images.githubusercontent.com/12200062/111050913-52b3ed80-8447-11eb-81b1-23ec6b2661b4.png)

**Comment by gokcinar** [comment]
> @Gregory-Gelfond I've implemented the feature as requested. The shortcode code [example](https://github.com/lxndrblz/anatole/blob/master/exampleSite/content/post/figure-shortcode.md) will give you something like this:
> 
> ![image](https://user-images.githubusercontent.com/12200062/111050913-52b3ed80-8447-11eb-81b1-23ec6b2661b4.png)

the link no longer works. can you update it?

**Comment by lxndrblz** [comment]
@gokcinar TYG:

https://github.com/lxndrblz/anatole/blob/master/exampleSite/content/english/post/figure-shortcode.md
