### ISSUE TITLE
website is showing the contents of readme file after publishing

### ISSUE THREAD

**Issue by rahulgadre** [lxndrblz/anatole#65]
Thank you for this template. I forked this repo and published it using Github pages. However, I am only seeing the contents of the readme file and not the actual blog site. What am I doing wrong? I plan to edit all the relevant files with my info after fixing this issue.
Any help regarding this matter will be helpful.

**Comment by lxndrblz** [comment]
If I look at the blog.rahulgadre.com repository it looks like you be just cloned the repository, but don't even have a Hugo site setup. You'll need a proper Hugo site first and then you can plugin any theme as a submodule or clone it.

Hope that helps.

**Comment by rahulgadre** [comment]
Thank you for your reply. I will set up a Hugo site first before attempting to use a theme. Apologies if it was very basic. I am a newbie into this space so I am learning as I go along.

**Comment by lxndrblz** [comment]
@rahulgadre Great! I'll go ahead and close the issue for the time being. Please reopen it if you have any more questions or if you encounter an issue related to the theme.
