### ISSUE TITLE
Always an about page?

### ISSUE THREAD

**Issue by jfmatth** [lxndrblz/anatole#73]
First, thank you for this Theme, I like it a lot.

Not sure how it's happening, but my menu always shows an about page.

I have an about.md defined in the content/ folder, but my config.toml doesn't specify one

```
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"
```

Any help is appreciated

**Comment by lxndrblz** [comment]
@jfmatth  Thanks for explaining your problem. I just tried to replicate your scenario (have an about.md but no entry in the config.toml). For me the about entry didn't come up (like it should). In the `navbar.html` partial, which is responsible for generating the menu are also no hard-coded entries. I, therefore, suspect that the error might come from your particular setup.

Here are a couple of questions, which might help us to narrow down your problem:

Would you mind sharing your complete `config.toml` (make sure to remove any sensitive data)?
Is it possible that you might have another menu entry or haven't saved the config file yet?
Are you by chance having a multi language setup?

**Comment by jfmatth** [comment]
thanks for the quick response, no worries, nothing sensitive

```
languageCode = "en-us"
theme = "anatole"
baseURL = "https://blog.stocksonthebeach.com"

[params]
  featured_image = "/images/beach-background.jpg"
  title = "StocksOnTheBeach.com"
  author = "John Matthew"
  description = "A simple blog"
  profilePicture="images/beach-background.jpg"
  favicon = "/img/favicon.ico"
  displayMode = "light"
  mainSections = ["posts"]


# Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/jfmatth/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url =  "https://github.com/jfmatth"



[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
```

I did switch themes from the ananke stock one to yours

if it matters, i'm serving it locally on my laptop for testing with this script
```
hugo server --bind 0.0.0.0 --baseURL primary.mshome.net
```

**Comment by jfmatth** [comment]
I did just run the sample, and it doesn't show an About.

I think what I'll do is just start fresh and see what happens, I don't have that much content yet

**Comment by jfmatth** [comment]
Well, I was able to find the issue.  For whatever reason, if there is an about.md file in my content folder, then the about menu item shows up, but doesn't point to the right file.

odd, seems like a HUGO bug
