### ISSUE TITLE
Could there be a limit for the content width? Thinking of ultrawide screens and so. 

### ISSUE THREAD

**Issue by ivnvitx** [lxndrblz/anatole#75]

**Comment by lxndrblz** [comment]
@ivnvitx Would you mind providing a screenshot or more detailed of the issue you are having? I assume it has to do with the fact, that the columns are stretched over the whole width of the screen.

**Comment by ivnvitx** [comment]
![imagen](https://user-images.githubusercontent.com/61422591/94174069-4f6e7a80-fe84-11ea-9331-c09731d22a73.png)

Yes, basically this is what would happen with wider screens and so. I was thinking if maybe there could be a limit on how much the website stretches horizontally. Many other websites do this very thing, so that the content does not stretch to far and your eyes get tired of moving so much.

**Comment by lxndrblz** [comment]
@ivnvitx  Gotcha, what we could do is to add a percentual margin for the content for high resolutions. This would look like the following:

![image](https://user-images.githubusercontent.com/12200062/94175604-cdd01a00-fe8e-11ea-9f88-3b4142fbba11.png)

**Comment by ivnvitx** [comment]
Yes, thank you for your work. 


The [picture you showed](https://github.com/lxndrblz/anatole/issues/75#issuecomment-698465174) is definitely better but at the same time, it would be better if no space was generated between the sidebar and the content. 

I feel like maybe the best approach would be to somehow keep both sides kinda together in the center, leaving blank space on the sides, or pushing everything to the left and leave a blank space on the right. I wish I (noob) could help out on this. I'll try when I get a bit of time.

**Comment by lxndrblz** [comment]
@ivnvitx I got an ultrawide screen the other day- so I'll be able to do some testing. I'm totally with you that centring the whole page would be the best approach. From what I've seen that's also the approach most other websites take.

**Comment by LITUATUI** [comment]
The sidebar does look too big in most desktop screens.

**Comment by lxndrblz** [comment]
@LITUATUI  Thanks for the feedback. I am working on the ultra-widescreen topic. For the time being you can also use a custom CSS file to shrink the column width.

**Comment by LITUATUI** [comment]
Thanks @lxndrblz. Just did what you suggested to shrink the sidebar from 40 to 25 %, looks much better now.
