### ISSUE TITLE
Site rendering properly in local machine but not in Netlify/Github

### ISSUE THREAD

**Issue by rajganeshp** [lxndrblz/anatole#78]
My site is rendering correctly locally but it's not working properly online. I'm using Github/Netlify to deploy. I had similar issue with another TEMPLATE, and I had to set  cssIntegrity: false and jsIntegrity: false to make it work. I'm not sure if it will fix it, but I'm not sure where to place this to try. Any help will be appreciated. I like this Theme.. Look at my site at https://www.connectthoughts.com

**Comment by lxndrblz** [comment]
I assume your `baseURL` in the `config.toml` is wrong:

![image](https://user-images.githubusercontent.com/12200062/94305056-8453fd80-ff68-11ea-8d3b-b5edbd5b25bb.png)

**Comment by rajganeshp** [comment]
You saved my day. Thanks. Can you give a sample CSS to change font?

**Comment by rajganeshp** [comment]
Now when I render locally it's not working fine. Apologize for the
inconvenience. I even tried to change the base URL to 127.0.0.1
[image: image.png]

**Comment by lxndrblz** [comment]
What error are you getting? You should be fine by just going to localhost:1313 in your browser. Please do not try the IP (127.0.0.1) as this will result in a another CORS error.

**Comment by rajganeshp** [comment]
Okay using localhost seems to work. It was working before 127.0.0.1

**Comment by lxndrblz** [comment]
I just remembered, we had similar issue before. See #48

Honestly, I am always going through localhost and never had an issue. That's also the Hugo recommendations as far as I know.

Please go ahead and close the issue if it is working now. 👍
