### ISSUE TITLE
What about showing what section you are in in the top bar in mobile navigation, instead of just the menu button?

### ISSUE THREAD

**Issue by ivnvitx** [lxndrblz/anatole#79]
Basically, where the cursor is. I think showing "Home", "About", and stuff would make it really cool for knowing where you are. 
![imagen](https://user-images.githubusercontent.com/61422591/95013700-846f8f80-0631-11eb-9f87-23244928fa52.png)

**Comment by lxndrblz** [comment]
@ivnvitx Thanks for bringing up this idea.

I had thought about it for a while and I can't (currently) see the need for it. However, if you want to submit a PR, I wouldn't mind reviewing it!

**Comment by LITUATUI** [comment]
The website name or logo would also look cool in that empty space.

**Comment by lxndrblz** [comment]
@LITUATUI I’m not building this feature at the moment, but it’s a vaid suggestion and contributions are always welcome!
