### ISSUE TITLE
Social icon not showing

### ISSUE THREAD

**Issue by MakoReactor** [lxndrblz/anatole#85]
Hello, My social icons is not showing. I Tried some tips on the others issues but, no success.
Localy they appear, but on Netlify not.

![icons-not-show](https://user-images.githubusercontent.com/368437/97702727-38780500-1a8e-11eb-9f8c-98b6f0cc598a.png)

This is my config.toml and is my link https://silly-payne-12666a.netlify.app/

baseURL = "https://silly-payne-12666a.netlify.app/"
languageCode = "en-us"
theme = "anatole"
summarylength = 30
enableEmoji = true
enableRobotsTXT = true
# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Dougs' Café"
author = "Douglas Barbosa"
description = "Olá, Seja bem vindo ao meu blog."
profilePicture = "images/profile.png"
displayMode = "dark"
#googleSiteVerify = ""
#googleAnalytics = ""
keywords = "blog"
favicon = "favicons/"
mainSections = ["posts"]
# Google Site Verification
#googleSiteVerify = "valid google"
images = ["images/profile.png"]

## Social links
[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/mako_reactor"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:douglas.santosb@gmail.com"

## menu links

[menu]
[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "Sobre"
weight = 300
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Tags"
weight = 400
identifier = "tags"
url = "/tags/"

[[menu.main]]
name = "Categorias"
weight = 500
identifier = "categories"
url = "/categories/"

**Comment by lxndrblz** [comment]
Hi there, thanks for your issue.

Please note, that we had some [breaking changes](https://github.com/lxndrblz/anatole/releases/tag/v0.3.1) in FontAwesome recently.

You will now need to prefix your social icons:

```yaml
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/mako_reactor"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:douglas.santosb@gmail.com"
```
Please let me know if that helped.

**Comment by MakoReactor** [comment]
Thanks,  I'll check and report.

**Comment by MakoReactor** [comment]
> 
> 
> Hi there, thanks for your issue.
> 
> I saw that you are having some Content Security Policy Issues:
> ![image](https://user-images.githubusercontent.com/12200062/97703808-29eb1700-1aa9-11eb-97df-562839935cbf.png)
> 
> You would need to adjust the CSP accordingly. The ReadMe contains a [section](https://github.com/lxndrblz/anatole#content-security-policy) on how to do that. I've noted earlier that the instructions on the readme might be outdated, as font-awesome is now using a different CDN. I've updated those now. Would you mind recreating your CSP?
> 
> Please let me know if that helped.
Yes, it's works thank you so much for your helping.

**Comment by lxndrblz** [comment]
@MakoReactor  Any update?
