### ISSUE TITLE
Inlined math is not rendered

### ISSUE THREAD

**Issue by kosii** [lxndrblz/anatole#88]
I'm having issues with inlined math expressions. I'd appreciate if you could have a look.

Hugo version: 0.77.0
Browsers: Chrome/Firefox/Safari

Reproduce:
1. Clone the latest version of anatole
```
git clone https://github.com/lxndrblz/anatole.git anatole
cd anatole/exampleSite
hugo server --themesDir ../..
```
2. Go to http://localhost:1313/post/math-typesetting/
3. The paragraph from the examples with the inlined math is missing

**Comment by lxndrblz** [comment]
I assume this is caused by latest change in the default content provided by the Hugo authors.

Unfortunately the documentation surrounding this issue is a bit sparse. 

For now you can use inline math like this:
`Inline math: \\(\varphi = \dfrac{1+\sqrt5}{2}= 1.6180339887…\\)`

**Comment by kosii** [comment]
It worked, thank you!
