### ISSUE TITLE
Example Site Code does not match Sample Pictures

### ISSUE THREAD

**Issue by jd4900** [lxndrblz/anatole#9]
Hi! Thanks for this template. 

I am setting up my website and am noticing some deviations between the base code and the pictures. For example, the menu in the sample picture has an About page but in the `config.toml` there is no about page listed. 

Is it possible to update the example site so it is easier to follow along with the template?

**Comment by jd4900** [comment]
Nevermind! I see what I am doing wrong. 🙃

**Comment by lxndrblz** [comment]
Hi there. Sorry for the late reply.

I've tweaked the toml file in a way that it's now displaying the about page, without having to define a custom frontmatter. :)
