### ISSUE TITLE
Safari not showing icons, while chrome/firefox are

### ISSUE THREAD

**Issue by jakevossen5** [lxndrblz/anatole#92]
I am having an issue with the safari on macOS and iOS not showing the icons for email / linkedin, while Firefox and Chrome are. This happens when I run locally and when I publish to S3/cloudfront. There are no errors in the console - any ideas?

Website is https://jake.vossen.dev.

Not sure if it will help, but the Safari dev tools seem to have `social-links` have the property `display: none;`

![Screen Shot 2020-11-23 at 11 10 36 PM](https://user-images.githubusercontent.com/16298666/100055451-1b122e80-2de1-11eb-93a7-3bbc66a03001.png)

**Comment by lxndrblz** [comment]
@jakevossen5  Thanks for bringing this to my attention. Somehow 
Would you mind sharing a screenshot of how it currently looks?

Unfortunately, I don't have access to an iOS or Apple device. However, it showed up correctly on browser stack. 
![image](https://user-images.githubusercontent.com/12200062/100157687-dc44ad00-2ea2-11eb-866b-a732d04fc2cf.png)

This makes me think that it's probably only a caching issue.

**Comment by jakevossen5** [comment]
![Uploading 8BF0A146-F738-4D9C-A166-8B21AB376178.png…]()

**Comment by jakevossen5** [comment]
Here is the post on my iPhone XSMax
![8BF0A146-F738-4D9C-A166-8B21AB376178](https://user-images.githubusercontent.com/16298666/100255362-a1716200-2f00-11eb-9361-2b29e6b15c48.png)

Here is a side by side with Safari and Firefox
<img width="817" alt="Screen Shot 2020-11-25 at 9 25 47 AM" src="https://user-images.githubusercontent.com/16298666/100255432-b8b04f80-2f00-11eb-9041-a8d3faabff01.png">

Just a quick note, I am running a fork of this project at https://github.com/jakevossen5/anatole/, the only difference is the index.html is a single page instead of a list of posts.

**Comment by lxndrblz** [comment]
Thanks for sharing the screenshots. Wow, this is really odd! 

One more question: Do you see the social icons on other anatole websites such as mine: www.alexbilz.com ?

When I visited your site earlier, I'd noticed that there is a CSP warning. Please make sure you have a correct `_headers` file in the static folder (see the readme for the exact content).

**Comment by jakevossen5** [comment]
I do not see the icons on that site (at least on my phone, not at my Mac right now)

![image](https://user-images.githubusercontent.com/16298666/100271228-6417cf00-2f16-11eb-8b1d-9d9aaaab433a.png)

And yeah, I think I got CSP fixed, my CDN just hasn't updated everywhere yet.

**Comment by lxndrblz** [comment]
@jakevossen5 Do you have any plugin in your browser enabled, which might explain this behavior?

I've checked today on another iPhone and couldn't reproduce the issue. 😔

**Comment by jakevossen5** [comment]
Ugh, I am sorry. I had [1blocker](https://1blocker.com/) installed on both my Phone and Mac and wasn't thinking about it, blocking social media buttons is an option in the settings.
