### ISSUE TITLE
Is there any simple way to make the sidebar not refresh when navigating on the webpage? 

### ISSUE THREAD

**Issue by ivangjxyz** [lxndrblz/anatole#93]
I find it specially irritating due to the profile pic having to reappear every time. It takes a split second, but you know... I'm being very very perfectionist here. Is there any way to tell the browser "just keep this here, update the rest"?

**Comment by lxndrblz** [comment]
@ivangjxyz Thanks for your question. Unfortunately, this is not possible due to the static nature of Hugo. There is no way to dynamically load content like ajax sides would do.

**Comment by ivangjxyz** [comment]
Perfect, then I'll try to minimize its weight as much as possible.
