### ISSUE TITLE
Math not showing up? (noob question)

### ISSUE THREAD

**Issue by jhilker1** [lxndrblz/anatole#95]
Hey there, I'm new to Hugo and I really like this theme - I'm using it on my [personal website](https://jhilker.gitlab.io). I've enabled math in my `config.toml`, however, I'm not seeing any LaTeX rendered (I've read over some of the documentation for katex). I copied the math.html from the layouts directory in the theme to the layouts folder in the base directory, but still no luck. Do you have any suggestions?

I'd also like to change the title of the website - would i need to edit the templates for every single layout?

Thanks for making this! It's a really clean theme.

**Comment by lxndrblz** [comment]
@jhilker1 Glad you like the theme!

There is no need to copy the math.html file, as they will be included automatically. Would you mind sharing how your LaTeX function looks? Either way should work, once either the global math setting or the one per Post is enabled.

```
Inline math: \\(\varphi = \dfrac{1+\sqrt5}{2}= 1.6180339887…\\)

Block math:
$$
 \varphi = 1+\frac{1} {1+\frac{1} {1+\frac{1} {1+\cdots} } } 
$$

```

The page title is composed like this: 
`<title> {{.Site.Params.author}}{{ with .Title }} | {{ . }}{{ end }} </title> `
All you need to do is to set the author variable in the `config.toml` and the title variable for each page/post. If you want anything different displayed in the title, you would have to alter the `head.html`.

Hope that helps.

**Comment by jhilker1** [comment]
Thanks! I got it figured out :)

Thanks,
Jacob Hilker
